### ISSUE TITLE
dart2js TypeImpl overrides operator ==

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#17207]
The equality operator is overridden for dart2js' Type implementation TypeIpml.

This means that it cannot be used in switch statements or as keys in constant maps.

See issue #15295 and issue #17123.

**Comment by lexaknyazev** [comment]
Apparently, this is somehow fixed with CFE.

**Comment by sigmundch** [comment]
Note - the CFE is missing some compile-time errors. I believe this is not actually fixed, since we still override `==` in our implementation of Type, so I expect this error should be visible again in the near future.

**Comment by sigmundch** [comment]
I just filed #32557 reporting why the CFE is not handling this error at this time. The underlying issue in dart2js remains, so I recommend not using Types as const keys or values on switch cases at this time, since it will be an error again soon.

**Comment by rakudrama** [comment]
The language specification currently treats type literals specially:

"Every instance of type `Type` which was originally obtained by evaluating a constant type literal 
has a primitive operator `==`."

I read this as permitting TypeImpl to override `==`, but the implementation is known to the compiler and runtime, just like the implementation of `Object.==` is known to the compiler and runtime, so constant type literals are permitted as case expressions and constant map keys.

**Comment by sigmundch** [comment]
We are very close to be able to mark this issue as fixed.

The new RTI is now enabled by default since 2.8.0-dev.1.0. This already makes switch cases work properly because our types are properly canonicalized. One issue remains is that we still override operator== in `_Type` (the equivalent of TypeImpl in the new RTI), but given our canonicalization rules we should be able to remove that.

@rakudrama - @fishythefish and I assume that's safe to remove at this point, correct?

**Comment by sigmundch** [comment]
`==` was removed in 3c2a6c26e25533dadaafc14d22e7434953f8da96
