### ISSUE TITLE
Analysis Server doesn't provide highlighting information for analysis_options.yaml file on Windows

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#25114]
OS specific issues. May be related to #24796. DAS returns empty set of problems for this file on Windows:

```
analyzer:
  errors:
    invalid-option: invalid-value
```

**Comment by alexander-doroshko** [comment]
@pq Windows users still have no error highlighting and code completion in `.analysis_options` files. Are there OS-specific technical difficulties with it?
Thanks for taking a look!

**Comment by pq** [comment]
@alexander-doroshko : I believe this is fixed?

Please re-open if you see otherwise.

**Comment by alexander-doroshko** [comment]
@pq I'm afraid it is not fixed. 
Analysis Server on Windows doesn't report errors/warnings neither for `.analysis_options` nor for `analysis_options.yaml` files. 
I do not have permissions to reopen the issue.

**Comment by pq** [comment]
Whoops.  Thanks for following up!  (And @bwilkerson  for re-opening!)

**Comment by devoncarew** [comment]
ping - this would be good to address

**Comment by pq** [comment]
fyi @jwren

**Comment by alexander-doroshko** [comment]
Update as of Dart SDK 2.10.0-110.3.beta on Windows:
- Server is reporting warnings like 'invalid option' or 'invalid value' in `analysis_options.yaml`
![image](https://user-images.githubusercontent.com/4499789/94010246-5925ae80-fdae-11ea-8c5d-550797242d5e.png)
- Note: warnings are reported only for *saved* state of the file, they are not updated on typing until the file is saved again. Is this a known limitation?
- Still no code completion in `analysis_options.yaml`.

**Comment by bwilkerson** [comment]
> warnings are reported only for saved state of the file, they are not updated on typing until the file is saved again. Is this a known limitation?

Yes.

> Still no code completion in analysis_options.yaml.

I believe that Jaime has been looking into this. @jwren

**Comment by srawlins** [comment]
This is a big feature for analyzer on other platforms, so definitely a big bug if we still don't report anything for analysis_options.yaml on Windows.

**Comment by bwilkerson** [comment]
Only updating on save is intentional. When an analysis options file is modified we have to re-analyze all of the files that depend on it, which in a large project could be everything in several packages. Reanalyzing that much on every few keystrokes isn't likely to be performant enough to make it practical.

**Comment by DanTup** [comment]
Oops, my comment was a bit vague. I understood this was deliberate, and what I meant to indicate was that unless this issue was tracking changing that (I don't think it is), the other things here may have been fixed along the way so (unless there's something specific to IntelliJ / legacy protocol on Windows), this issue could be closed?

**Comment by bwilkerson** [comment]
Yes, I think we can close this. We can always re-open it if there's a reason to leave it open.
