### ISSUE TITLE
"dart.exe has stopped working" on Windows when doing "pub run test" (Dart SDK 1.13.1+)

### ISSUE THREAD

**Issue by corgrath** [dart-lang/sdk#25345]
OS: Windows 10 64bit
Dart SDK version: 1.13.1
Test library version: 0.12.6+2
Terminal: cmder 1.1.4.1 (but problem also exists using Window's cmd terminal)

Test test suit does go through, but each time I get a Windows "dart.exe has stopped working".

Just doing `dart test.dart` gives no problems at all.

I don't know if there are any logs I can attach to help with the bug report.

The test is the sample test from the test library's documentatoin

```
import "package:test/test.dart";

void main( ) {
    test("String.split() splits the string on the delimiter", ( ) {
        var string = "foo,bar,baz";
        expect(string.split(","), equals(["foo", "bar", "baz"]));
    });

    test("String.trim() removes surrounding whitespace", ( ) {
        var string = "  foo ";
        expect(string.trim(), equals("foo"));
    });
}
```

![image1](https://cloud.githubusercontent.com/assets/472514/12120172/e301b4d8-b3cf-11e5-9938-7cbb580353b1.png)

**Comment by floitschG** [comment]
Also /ccing @whesse for the 'find: > ...' when running pub run test.
Note that `pub run test --version` does not yield the "dart.exe has stopped working" (confirmed via IRC).

**Comment by floitschG** [comment]
Also ccing @nex3 and @munificent. Maybe they can help reduce the example.

**Comment by nex3** [comment]
Without a stack or something, I'm not sure what would be going on here. I'm not familiar enough with Windows to even know the general categories of failures that would cause an error like this. As far as I know, the test package isn't doing anything particularly unusual here—just starting up some isolates.

**Comment by corgrath** [comment]
Given instructions, I can try and generate additional logs.

**Comment by nex3** [comment]
Try running `pub --verbose run test test.dart`. I'm not sure if that will capture this particular failure, but it's worth a shot.

**Comment by corgrath** [comment]
Executing `put --verbose run test test.dart`

```
λ pub --verbose run test test.dart
find: >     bin [: No such file or directory
FINE: Pub 1.13.1
IO  : Spawning "cmd /c ver" in c:\christoffer\labs-chat-service\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | |
    | | Microsoft Windows [Version 10.0.10240]
    | Nothing output on stderr.
00:00 +0: String.split() splits the string on the delimiter
00:00 +1: String.trim() removes surrounding whitespace
00:00 +2: All tests passed!
```

**Comment by nex3** [comment]
Nothing useful there I'm afraid.

**Comment by corgrath** [comment]
Error output from Windows Viewer - Windows Logs - Application - Application Error

```
Faulting application name: dart.exe, version: 0.0.0.0, time stamp: 0x5672c99d
Faulting module name: dart.exe, version: 0.0.0.0, time stamp: 0x5672c99d
Exception code: 0xc0000005
Fault offset: 0x0000000000042482
Faulting process ID: 0x6510
Faulting application start time: 0x01d14802dad6d821
Faulting application path: C:\christoffer\Dropbox\applications\dart-sdk-1-13-1\bin\dart.exe
Faulting module path: C:\christoffer\Dropbox\applications\dart-sdk-1-13-1\bin\dart.exe
Report ID: 371b3117-feaf-4b9e-8a5b-0ecb64c23e85
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by corgrath** [comment]
Error output from Windows Viewer - Windows Logs - Application - Information

```
Fault bucket 120376049294, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: dart.exe
P2: 0.0.0.0
P3: 5672c99d
P4: dart.exe
P5: 0.0.0.0
P6: 5672c99d
P7: c0000005
P8: 0000000000042482
P9: 
P10: 

Attached files:
C:\Users\Christoffer\AppData\Local\Temp\WERD3DB.tmp.WERInternalMetadata.xml
C:\Users\Christoffer\AppData\Local\Temp\WERD989.tmp.appcompat.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_dart.exe_63621e13f983676824935f107e3450a46d24ef5_82514f5c_ecf1d9b7

Analysis symbol: 
Rechecking for solution: 0
Report ID: 371b3117-feaf-4b9e-8a5b-0ecb64c23e85
Report Status: 1
Hashed bucket: 9141ebe23f52465985f017222c4fdac5
```

**Comment by fsc8000** [comment]
Looks like a crash bug in the Dart VM. Can you check if it also occurs with the latest stable SDK version 1.13.2?

**Comment by corgrath** [comment]
Same results for `1.13.2`.

![dart1132](https://cloud.githubusercontent.com/assets/472514/12147514/a2aee174-b499-11e5-8cfe-ead0881f5506.png)

**Comment by fsc8000** [comment]
This crash may already have been fixed on the dev channel. I tried with the bleeding edge (1.14.0) and could not reproduce the crash. Any chance you could try a dev-channel SDK?

"""
C:\src\regress25345>..\dartgit\sdk\build\ReleaseX64\dart-sdk\bin\dart --version
Dart VM version: 1.14.0-edge.c6f0d75d81a4a45817be1516449e1d3fe04be223 (Thu Jan 07 14:06:05 2016) on "windows_x64"

C:\src\regress25345>..\dartgit\sdk\build\ReleaseX64\dart-sdk\bin\pub run test test.dart
00:00 +0: String.split() splits the string on the delimiter
00:00 +1: String.trim() removes surrounding whitespace
00:00 +2: All tests passed!
"""

**Comment by corgrath** [comment]
`1.14.0-dev.6.0 (ref 4777b2c)` failed.

![14](https://cloud.githubusercontent.com/assets/472514/12191901/038f8c8c-b5da-11e5-9d6c-e75f736ffd92.png)

**Comment by corgrath** [comment]
If given an instrumented and verbose build, I can probably give a better log.

**Comment by fsc8000** [comment]
Hm, that's strange. I still can't reproduce it. Is it always crashing, or just every once in a while? Let's make sure 
```
C:\src\regress25345>..\dartgit\sdk\build\ReleaseX64\dart --version
Dart VM version: 1.14.0-dev.6.0 (Mon Jan 11 12:38:11 2016) on "windows_x64"
```

```
C:\src\regress25345>..\dartgit\sdk\build\ReleaseX64\dart-sdk\bin\pub run test test.dart
00:00 +0: String.split() splits the string on the delimiter
00:00 +1: String.trim() removes surrounding whitespace
00:00 +2: All tests passed!

C:\src\regress25345>..\dartgit\sdk\build\ReleaseX64\dart-sdk\bin\pub run test test.dart
00:00 +0: String.split() splits the string on the delimiter
00:00 +1: String.trim() removes surrounding whitespace
00:00 +2: All tests passed!
```

Let's make sure, the repro is the same as yours: Here is what I use as pubspec.yaml:


```
name: regress25345
dependencies:
  test: any
```

and here is test.dart

```dart
import "package:test/test.dart";

void main( ) {
    test("String.split() splits the string on the delimiter", ( ) {
        var string = "foo,bar,baz";
        expect(string.split(","), equals(["foo", "bar", "baz"]));
    });

    test("String.trim() removes surrounding whitespace", ( ) {
        var string = "  foo ";
        expect(string.trim(), equals("foo"));
    });
}
```

am I missing something from the reproduction?

**Comment by corgrath** [comment]
I will do a complete isolated test, similar to what you have done and report back.

**Comment by corgrath** [comment]
I litterally just downloaded the `1.14.0-dev.6.0`

https://storage.googleapis.com/dart-archive/channels/dev/release/1.14.0-dev.6.0/sdk/dartsdk-windows-x64-release.zip

Unpacked it.
Went into the dart-sdk\bin\ folder and created pubspec.yaml with this contents:

```
name: regress25345
dependencies:
  test: any
```

Did `pub install`.

Created `test.dart` containing, encoded with ANSI (but I get the same results with UTF-8):

```
import "package:test/test.dart";

void main( ) {
    test("String.split() splits the string on the delimiter", ( ) {
        var string = "foo,bar,baz";
        expect(string.split(","), equals(["foo", "bar", "baz"]));
    });

    test("String.trim() removes surrounding whitespace", ( ) {
        var string = "  foo ";
        expect(string.trim(), equals("foo"));
    });
}
```

And it fails

![image14](https://cloud.githubusercontent.com/assets/472514/12258966/c053e814-b912-11e5-8be5-5688a33f666f.png)

**Comment by corgrath** [comment]
I can record the whole test using a screen capture app, if you want.
I can also ZIP the whole folder to a dropbox link.

I am getting this problem one two separated Windows machines.

**Comment by fsc8000** [comment]
Thanks for trying this. It looks like the tests pass and then the VM crashes. It seems that there is a crash bug in the  shutdown of the dart process. I'll investigate more.

**Comment by fsc8000** [comment]
I tried Windows 7 only so far. I'll try a Windows 10 machine as well. It could be the Windows version that makes it reproduce. @zanderso is working on fixing VM shutdown issues. I'll keep this issue updated when we have a potential fix.

**Comment by alexander-doroshko** [comment]
100% reproducible for me as well (Windows 8.1), also with the latest SDK 1.14-dev.7.0.
At the same time I'm pretty sure I did the same last week but didn't have "dart.exe has stopped working" error. May be related to the Windows updates that I installed yesterday.

**Comment by alexander-doroshko** [comment]
@fsc8000 @zanderso Sorry for the ping, 'Milestone' is not set for this issue. Will it be addressed in SDK 1.14? Seeing that Dart VM crashes multiple times a day (when I run tests in WebStorm or IntelliJ IDEA) makes me nervous.

**Comment by mraleph** [comment]
Fixed with 89121bf530b1b25686597f5b1e03c16de9ae3023.

**Comment by MikeMitterer** [comment]
Seems not fixed. I have the same problem but under Mac OSX
- OS ---------------------------------------------------------------------------
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34
Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

- Software installed -----------------------------------------------------------
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Dart VM version: 1.17.1 (Fri Jun 10 04:46:03 2016) on "macos_x64"
Pub 1.17.1

**Comment by zanderso** [comment]
@MikeMitterer You are probably seeing a different bug. Could you please file a new issue with reproduction instructions. Thanks!
