### ISSUE TITLE
Analysis errors on dart:html with Chrome 45 roll 

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/sdk#25928]
These cause an analysis test to fail, and probably reflect real bugs, or at least changes we need to make in the code.

sdk/lib/html/dart2js/html_dart2js.dart:43130:1:
Warning: 'KeyEvent' doesn't implement the getter 'sourceDevice' declared in 'UIEvent'.
Try adding an implementation of 'sourceDevice' or declaring 'KeyEvent' to be 'abstract'.
class KeyEvent extends _WrappedEvent implements KeyboardEvent {
^^^^^
sdk/lib/html/dart2js/html_dart2js.dart:33410:21:
Info: The getter 'sourceDevice' is implicitly declared by this field in class 'UIEvent'.
  final InputDevice sourceDevice;
                    ^^^^^^^^^^^^
sdk/lib/html/dart2js/html_dart2js.dart:43130:1:
Warning: 'KeyEvent' doesn't implement the getter 'code' declared in 'KeyboardEvent'.
Try adding an implementation of 'code' or declaring 'KeyEvent' to be 'abstract'.
class KeyEvent extends _WrappedEvent implements KeyboardEvent {
^^^^^
sdk/lib/html/dart2js/html_dart2js.dart:21455:16:
Info: The getter 'code' is implicitly declared by this field in class 'KeyboardEvent'.
  final String code;
               ^^^^
sdk/lib/html/dart2js/html_dart2js.dart:43130:1:
Warning: 'KeyEvent' doesn't implement the getter 'key' declared in 'KeyboardEvent'.
Try adding an implementation of 'key' or declaring 'KeyEvent' to be 'abstract'.
class KeyEvent extends _WrappedEvent implements KeyboardEvent {
^^^^^
sdk/lib/html/dart2js/html_dart2js.dart:21464:16:
Info: The getter 'key' is implicitly declared by this field in class 'KeyboardEvent'.
  final String key;
               ^^^
sdk/lib/html/dart2js/html_dart2js.dart:33439:31:
Warning: No member named '_pageX' in class 'UIEvent'.
  Point get page => new Point(_pageX, _pageY);
                              ^^^^^^
sdk/lib/html/dart2js/html_dart2js.dart:33439:39:
Warning: No member named '_pageY' in class 'UIEvent'.
  Point get page => new Point(_pageX, _pageY);
                                      ^^^^^^
sdk/lib/html/dart2js/html_dart2js.dart:33435:32:
Warning: No member named '_layerX' in class 'UIEvent'.
  Point get layer => new Point(_layerX, _layerY);
                               ^^^^^^^
sdk/lib/html/dart2js/html_dart2js.dart:33435:41:
Warning: No member named '_layerY' in class 'UIEvent'.
  Point get layer => new Point(_layerX, _layerY);
                                        ^^^^^^^
sdk/lib/html/dart2js/html_dart2js.dart:43290:37:
Warning: No member named 'clipboardData' in class 'KeyboardEvent'.
  DataTransfer get clipboardData => _parent.clipboardData;
                                    ^^^^^^^^^^^^^^^^^^^^^
sdk/lib/html/dart2js/html_dart2js.dart:43376:37:
Warning: No member named 'clipboardData' in class 'Event'.
  DataTransfer get clipboardData => wrapped.clipboardData;
                                    ^^^^^^^^^^^^^^^^^^^^^

**Comment by sigmundch** [comment]
Thanks for filing, I noticed these recently too.

Here is a test that fails because of this:
```
./tools/test.py -m release dart2js/analyze_api_test
```

**Comment by terrylucas** [comment]
Yes I have a partial fix I check-in soon.

**Comment by whesse** [comment]
These failures are now whitelisted in tests/compiler/dart2js/analyze_api_test.dart, and should be removed when they are fixed.  CL is https://codereview.chromium.org/1773583002

**Comment by terrylucas** [comment]
Fixed with this CL [https://codereview.chromium.org/1754523006/](https://codereview.chromium.org/1754523006/)

**Comment by sigmundch** [comment]
It appears that we still have these failures in the bots:
https://build.chromium.org/p/client.dart/builders/dart2js-linux-jsshell-4-4-be/builds/59/steps/dart2js%20unit%20tests/logs/stdio

**Comment by sigmundch** [comment]
Ah, I think I understand what happened. It appears that your fix did not eliminate all the warnings, but concurrently Florian submitted a change in dart2js that modified the error messages.

The new error messages didn't match the whitelist, so we said those errors in the whitelist were unused and gave you the false impression that all errors were gone. I just submitted the updated error messages in the white list here: https://github.com/dart-lang/sdk/commit/43f943245e09302b31ff1f995f17d37336f43b63

**Comment by athomas** [comment]
Closing, looks like it was fixed years ago.
