### ISSUE TITLE
Analyzer chokes on async regression test language/regress_26668_test

### ISSUE THREAD

**Issue by crelier** [dart-lang/sdk#26678]
FAILED: dart2analyzer-none release_ia32 language/regress_26668_test
Expected: Pass 
Actual: StaticWarning
CommandOutput[dart2analyzer]:

stderr:
WARNING|STATIC_TYPE_WARNING|RETURN_OF_INVALID_TYPE|/b/build/slave/analyzer_experimental-linux-release-be/build/sdk/tests/language/regress_26668_test.dart|15|12|1|The return type 'Future<int>' is not a 'Future<T>', as defined by the method 'processData'.

Command[dart2analyzer]: DART_CONFIGURATION=ReleaseIA32 sdk/bin/dartanalyzer --ignore-unrecognized-flags --show-package-warnings --enable-async --package-root=out/ReleaseIA32/packages/ --machine --no-hints /b/build/slave/analyzer_experimental-linux-release-be/build/sdk/tests/language/regress_26668_test.dart
Took 0:00:00.012546

Short reproduction command (experimental):
    python tools/test.py -mrelease -aia32 -cdart2analyzer -rnone --write-debug-log --write-test-outcome-log -t240 language/regress_26668_test

**Comment by srawlins** [comment]
This is fixed, yes? It works for me on bleeding edge.

**Comment by bwilkerson** [comment]
It is still marked as failing in the status file, so I assume that it isn't fixed.

**Comment by srawlins** [comment]
oh, i see, the repro command will always succeed if its in the status file 😛  ok fair.
