### ISSUE TITLE
No error in analyzer 1.20 if there are two part directives with the same url

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/sdk#27509]
```dart
library Parts_test_lib;
part "part_0.dart";
part "part_0.dart";

main() {
}
```
part_0.dart is the following
```dart
part of Parts_test_lib;
var foo;
```
There was an error in analyzer 1.19.1 "[error] The name 'foo' is already defined"
In dartanalyzer version 1.20.0-dev.10.1 "No issues found". Was this intentional?

**Comment by scheglov** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/26cc95d8b4ad09971cef55c196cc632de8f97be0

**Comment by fsc8000** [comment]
Not fixed: Consider running this program from a directory ```mydir```:

```
library Parts_test_lib;
part "part_0.dart";
part "../mydir/part_0.dart";

main() {
}
```
The correct error message is to report a duplicate declaration.

**Comment by scheglov** [comment]
https://codereview.chromium.org/2401783002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/59e8af70476a3806b813dbb9f386e32f0ad784ae
