### ISSUE TITLE
Specify generic methods in Dart 1.5, strong mode

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#27529]
For 1.50, there is no additional implementation support needed for generic methods in strong mode. The open issues that were to be decided are:

- Do we support first-class generic methods (almost certainly "yes")? **Yes**
- Can a non-generic be overridden with a generic method? **No**
- Do we allow partial instantiations (setting the generic types)? What would then be the equality/identity? **Not until after 1.50**

Given those, the VM, dart2js, et al. are in OK shape. What's left is to specify it, which is what this bug is for.

See also: https://github.com/dart-lang/dart-lang-evolution/issues/111

**Comment by floitschG** [comment]
Status update:
I updated the bug with the open questions.
Not all questions need to be answered for 1.50, but some are necessary.

**Comment by leafpetersen** [comment]
status: not started.

**Comment by munificent** [comment]
Update:

The answer to the first question is "yes".

For the other two, we can safely default to "no" for now if we don't get time to put it into 1.50, though we would like to look into them if we can.

**Comment by dgrove** [comment]
We definitely need final answers for 1.50 now.

**Comment by munificent** [comment]
Added it to next week's language meeting agenda.

**Comment by leafpetersen** [comment]
There is only one small feature left to be implemented for this.

We would like to add syntactic support for instantiating tear offs.  That is, anywhere that you can currently have an expression `e` which corresponds to a generic method (i.e. a tearoff, or a function expression) we would like you to be able to write an expression `e<T>` which denotes an instantiated version of `e`.  For example:

```dart
typedef void F(int x);

class A {
  void foo<T>(T x) {}
}

void bar<T>(T x) {}

void test() {
   // Direct method tearoff
   F f = (new A()).foo<int>;
   // Direct function tearoff
  f = bar<int>;
   // Function expression tearoff
   f = (bar)<int>;
}
```

@eernstg Can you add a more detailed syntax proposal for this to your spec for non-strong mode generic methods?

@crelier @a-siva  Is it reasonable to try to get syntax support for this in the VM in time for 1.5?  As usual, the type arguments would be ignored by the VM in 1.5.

**Comment by crelier** [comment]
It is difficult to answer without seeing the grammar first. As far as I know, parsing of generic functions depends on the presence of parentheses for disambiguation (implemented by @mhausner in the VM). What you are proposing looks harder to disambiguate.

**Comment by munificent** [comment]
We've decided to *not* support partial instantiations / generic tear-offs in 1.50. Because of that, there's no implementation work needed for this. It's just spec-ing the analysis we've already implemented.

**Comment by eernstg** [comment]
Just for the record: We discussed one possible strategy for ensuring that the generic tear-off / partial instantiation is syntactically unambiguous: Find a set of tokens indicating the end of the current construct (')', ']', '}', ',', ';', ...) and require such a token to occur right after the generic tear-off. This means that `var intMax = math.max<int>;`, `foo(bar<Null>)`, and `foo(bar<C, D>, 42)` will "just work", and every occurrence of a generic tear-off in a context where it isn't allowed according to this criterion could be made to work by enclosing it in parentheses (`(silly.invocation<int>)("baz")`).

**Comment by mit-mit** [comment]
> We've decided to not support partial instantiations / generic tear-offs in 1.50. Because of that, there's no implementation work needed for this. It's just spec-ing the analysis we've already implemented.

Would it make sense to remove the meta label/title from this, and use this as the area-specification bug?

**Comment by munificent** [comment]
Done. I hope that's what Leaf wanted. :)

**Comment by eernstg** [comment]
Work is ongoing: [This CL](https://dart-review.googlesource.com/c/sdk/+/14525) adds a Dart 2 specification (except that error is still spelled 'warning', and subtype rules are left untouched in their Dart 1.x form) of generic functions.

**Comment by leafpetersen** [comment]
@eernstg I think this is done now and can be closed?

**Comment by eernstg** [comment]
Yep!

Closing: As of [this commit](https://github.com/dart-lang/sdk/commit/673d5f0a665085153d25f8c39495eacdb010ca64), the language specification has been updated to specify generic methods for Dart 2, which subsumes the goal of this issue.
