### ISSUE TITLE
Ananlyzer crash in Atom

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/sdk#28464]
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

Typing in a class in a library that has a top level name:
```dart
final result = await db.query('...', {'parentId': input.parentId}).map(table.Category.map);
return new table.Category.from(result.first);
```
(I was typing `table.Category.map`)

### Versions

- Dart SDK 1.21.1
- Visual Studio Code 1.8.1
- Dart Code 0.14.9

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=0.14.9
```

### Exception

Failure in incremental resolver

```text
NoSuchMethodError: The getter 'isDynamic' was called on null.
Receiver: null
Tried calling: isDynamic
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _isBottom (package:analyzer/src/generated/type_system.dart:27)
#3      StrongTypeSystemImpl._isSubtypeOf (package:analyzer/src/generated/type_system.dart:903)
#4      StrongTypeSystemImpl.isSubtypeOf (package:analyzer/src/generated/type_system.dart:576)
#5      StrongTypeSystemImpl.inferGenericFunctionCall (package:analyzer/src/generated/type_system.dart:421)
#6      StaticTypeAnalyzer._inferGenericInvoke (package:analyzer/src/generated/static_type_analyzer.dart:2014)
#7      StaticTypeAnalyzer._inferGenericInvocationExpression (package:analyzer/src/generated/static_type_analyzer.dart:1934)
#8      StaticTypeAnalyzer.visitMethodInvocation (package:analyzer/src/generated/static_type_analyzer.dart:793)
#9      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7419)
#10     ResolverVisitor.visitMethodInvocation (package:analyzer/src/generated/resolver.dart:6297)
#11     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7419)
#12     AwaitExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1091)
#13     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#14     UnifyingAstVisitor.visitAwaitExpression (package:analyzer/dart/ast/visitor.dart:2511)
#15     ResolverVisitor.visitAwaitExpression (package:analyzer/src/generated/resolver.dart:5483)
#16     AwaitExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:1087)
#17     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10866)
#18     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#19     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:2816)
#20     ScopedVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:7736)
#21     ResolverVisitor.visitVariableDeclaration (package:analyzer/src/generated/resolver.dart:6436)
#22     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:10860)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#24     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:10958)
#25     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#26     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:2820)
#27     ResolverVisitor.visitVariableDeclarationList (package:analyzer/src/generated/resolver.dart:6462)
#28     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:10952)
#29     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11013)
#30     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#31     UnifyingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:2824)
#32     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:11009)
#33     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#34     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#35     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#36     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2517)
#37     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7237)
#38     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:7675)
#39     ResolverVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:6106)
#40     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5805)
#41     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#42     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#43     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#44     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2517)
#45     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7237)
#46     ScopedVisitor.visitStatementInScope (package:analyzer/src/generated/resolver.dart:7675)
#47     ResolverVisitor.visitIfStatement (package:analyzer/src/generated/resolver.dart:6106)
#48     IfStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:5805)
#49     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7814)
#50     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#51     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#52     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2517)
#53     ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:7237)
#54     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#55     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#56     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#57     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2520)
#58     ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:7249)
#59     ResolverVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5554)
#60     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#61     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5336)
#62     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#63     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:2631)
#64     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:7549)
#65     ResolverVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:6041)
#66     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5330)
#67     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5181)
#68     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:6309)
#69     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:2624)
#70     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:7542)
#71     ResolverVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:5999)
#72     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:7534)
#73     ResolverVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:5989)
#74     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5174)
#75     IncrementalResolver._resolveReferences (package:analyzer/src/generated/incremental_resolver.dart:370)
#76     IncrementalResolver.resolve (package:analyzer/src/generated/incremental_resolver.dart:260)
#77     PoorMansIncrementalResolver.resolve (package:analyzer/src/generated/incremental_resolver.dart:727)
#78     AnalysisContextImpl._tryPoorMansIncrementalResolution.<anonymous closure> (package:analyzer/src/context/context.dart:1937)
#79     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#80     AnalysisContextImpl._tryPoorMansIncrementalResolution (package:analyzer/src/context/context.dart:1900)
#81     AnalysisContextImpl.handleContentsChanged (package:analyzer/src/context/context.dart:1063)
#82     AnalysisServer.updateContent.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1528)
#83     List.forEach (dart:core-patch/growable_array.dart:258)
#84     AnalysisServer.updateContent.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1521)
#85     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:348)
#86     AnalysisServer.updateContent (package:analysis_server/src/analysis_server.dart:1466)
#87     AnalysisDomainHandler.updateContent (package:analysis_server/src/domain_analysis.dart:316)
#88     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:222)
#89     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:851)
#90     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#91     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:847)
#92     _rootRun (dart:async/zone.dart:1150)
#93     _CustomZone.run (dart:async/zone.dart:1026)
#94     _CustomZone.runGuarded (dart:async/zone.dart:924)
#95     runZoned (dart:async/zone.dart:1501)
#96     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:846)
#97     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:170)
#98     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#99     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161)
#100    ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110)
#101    _rootRunUnary (dart:async/zone.dart:1158)
#102    _CustomZone.runUnary (dart:async/zone.dart:1037)
#103    _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#104    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#105    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#106    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#107    _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#108    _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#109    _LineSplitterSink._addLines (dart:convert/line_splitter.dart:158)
#110    _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:133)
#111    StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#112    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#113    _rootRunUnary (dart:async/zone.dart:1158)
#114    _CustomZone.runUnary (dart:async/zone.dart:1037)
#115    _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#116    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#117    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#118    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#119    _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#120    _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#121    _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#122    _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#123    _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#124    _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#125    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#126    _rootRunUnary (dart:async/zone.dart:1158)
#127    _CustomZone.runUnary (dart:async/zone.dart:1037)
#128    _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#129    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#130    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#131    _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#132    _StreamController._add (dart:async/stream_controller.dart:635)
#133    _StreamController.add (dart:async/stream_controller.dart:581)
#134    _Socket._onData (dart:io-patch/socket_patch.dart:1680)
#135    _rootRunUnary (dart:async/zone.dart:1162)
#136    _CustomZone.runUnary (dart:async/zone.dart:1037)
#137    _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#138    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#139    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#140    _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#141    _StreamController._add (dart:async/stream_controller.dart:635)
#142    _StreamController.add (dart:async/stream_controller.dart:581)
#143    _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
#144    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:781)
#145    _microtaskLoop (dart:async/schedule_microtask.dart:41)
#146    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#147    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#148    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by hermanbergwerf** [comment]
I do not have this issue in `1.22.0-dev.9.1`. So this can probably be closed.

**Comment by bwilkerson** [comment]
Thanks for letting us know, and I'm glad the issue has been resolved!

**Comment by hermanbergwerf** [comment]
Unfortunately I now found this is not the case. It still crashes if there are other errors it seems. I added another stack trace below. (this one is different, but was generated in a similar way, in an existing project without errors I imported `'dart:io' as io`, typed some random stuff to generate errors, and then tried to autocomplete `io.`

### Versions

- Dart SDK 1.22.0-dev.9.1
- Visual Studio Code 1.8.1
- Dart Code 0.14.9

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=0.14.9
```

### Exception

Task failed: GatherUsedLocalElementsTask for source /home/herman/repos/eqdb/eqlib/lib/src/function.dart

```text
Unexpected exception while performing GatherUsedLocalElementsTask for source /home/herman/repos/eqdb/eqlib/lib/src/function.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:333)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:220)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1187)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1185)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:158)
#10     _rootRun (dart:async/zone.dart:1146)
#11     _CustomZone.run (dart:async/zone.dart:1026)
#12     _CustomZone.runGuarded (dart:async/zone.dart:924)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#14     _rootRun (dart:async/zone.dart:1150)
#15     _CustomZone.run (dart:async/zone.dart:1026)
#16     _CustomZone.runGuarded (dart:async/zone.dart:924)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by Bad state: Unable to find (int i) → Expr in [(null i) → dynamic]
#0      ElementImpl.findElementIndexUsingIdentical (package:analyzer/src/dart/element/element.dart:3162)
#1      FunctionElementImpl.identifier (package:analyzer/src/dart/element/element.dart:4402)
#2      ElementLocationImpl.ElementLocationImpl.con1 (package:analyzer/src/dart/element/element.dart:3202)
#3      ElementImpl.location (package:analyzer/src/dart/element/element.dart:2920)
#4      ElementImpl.hashCode (package:analyzer/src/dart/element/element.dart:2809)
#5      _HashSet._hashCode (dart:collection-patch/collection_patch.dart:564)
#6      _HashSet.add (dart:collection-patch/collection_patch.dart:600)
#7      UsedLocalElements.addElement (package:analyzer/src/generated/resolver.dart:10528)
#8      GatherUsedLocalElementsVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:3522)
#9      FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5346)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8043)
#11     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#12     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:605)
#13     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#14     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6490)
#15     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:935)
#16     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6485)
#17     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8043)
#18     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#19     RecursiveAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:605)
#20     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#21     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6490)
#22     RecursiveAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:935)
#23     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6485)
#24     ExpressionFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4093)
#25     RecursiveAstVisitor.visitExpressionFunctionBody (package:analyzer/dart/ast/visitor.dart:809)
#26     ExpressionFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:4089)
#27     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7535)
#28     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1007)
#29     GatherUsedLocalElementsVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:3532)
#30     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7526)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8043)
#32     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1991)
#33     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:683)
#34     GatherUsedLocalElementsVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3502)
#35     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#36     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8043)
#37     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#38     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#39     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#40     GatherUsedLocalElementsTask.internalPerform (package:analyzer/src/task/dart.dart:3105)
#41     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)
#42     AnalysisTask.perform (package:analyzer/task/model.dart:220)
#43     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#44     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#45     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1187)
#46     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#47     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1185)
#48     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:369)
#49     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:997)
#50     Future.Future.<anonymous closure> (dart:async/future.dart:158)
#51     _rootRun (dart:async/zone.dart:1146)
#52     _CustomZone.run (dart:async/zone.dart:1026)
#53     _CustomZone.runGuarded (dart:async/zone.dart:924)
#54     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#55     _rootRun (dart:async/zone.dart:1150)
#56     _CustomZone.run (dart:async/zone.dart:1026)
#57     _CustomZone.runGuarded (dart:async/zone.dart:924)
#58     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#59     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#60     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#61     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by bergwerf** [comment]
I am not using Atom anymore (and haven't been for almost a year now) and I can imagine this issue is no longer relevant. So I am closing this issue.
