### ISSUE TITLE
dart2js: Problem with type inference of do-while loop

### ISSUE THREAD

**Issue by sergey-o** [dart-lang/sdk#29309]
```dart
import 'dart:html';

void main() {
  WebSocket socket;
  do {
    socket = new WebSocket('ws://127.0.0.1:12345/');
  } while (socket == null);
  socket.onClose.listen((CloseEvent event) => print(event.type));
}
```
dart2js compiles this without errors.

Expected output in the browser console (can be seen by replacing the `do...while` loop with `while`):

```
close
```

Actual output:

```
TypeError: $event.get$type is not a function
```

Tested on Dart 1.22.1 and 1.23.0-dev.11.6, 64-bit Linux.

**Comment by rakudrama** [comment]
This is a problem with global type inference on do-while loops.
The analysis seems to think that `socket == null` is true on both the back-edge and the exit edge.

**Comment by rakudrama** [comment]
I'm closing this since the bad code generation problem is fixed by the work-around and future enhancements to global type analysis will be done on kernel-ir, which does not have do-while.

**Comment by sigmundch** [comment]
(reopening because we do have a do-while in kernel now, the issue still exists).
