### ISSUE TITLE
Upgrading hints to warnings in `analysis_options` doesn't fail the CLI with --fatal-warnings

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#29423]
Seen in both `1.23.0` gold and `1.24.0-dev.0.0`

See https://github.com/dart-lang/angular_components/tree/analyzer_issue

Here's the warning-causing code: https://github.com/dart-lang/angular_components/commit/3a27e7ed74055b73c09cc9583fdc899e68397685

Here's the `analysis_options` tweaks: https://github.com/dart-lang/angular_components/commit/915653756842acd6a64934150df0a40cd5f7240f

Here's me telling travis to run analyzer with `fatal-warnings` https://github.com/dart-lang/angular_components/commit/6e23a5d9e8dd62d6bd7581c24dd3f18935ac36e4#diff-354f30a63fb0907d4ad57269548329e3R8

Here's the warning being found during the run: https://travis-ci.org/dart-lang/angular_components/jobs/224447492#L251

Here's analyzer reporting 4 warnings: https://travis-ci.org/dart-lang/angular_components/jobs/224447492#L1019

Here's analyzer returning exit code `0` - https://travis-ci.org/dart-lang/angular_components/jobs/224447492#L1022

**Comment by bwilkerson** [comment]
@devoncarew Is this something that you could look at as part of removing duplicated errors?

**Comment by devoncarew** [comment]
This seems like a separate issue (in related code). The CL to fix duplicate issues has landed. The code to promote hints -> warnings and warnings -> errors in dartanalyzer does need a bunch of cleanup - it's done in a few different places.

**Comment by devoncarew** [comment]
I'll take a look at this and see if I'm able to track down the issue.

**Comment by kevmoo** [comment]
FYI: we can separate out the `--fatal-warnings` flag here, too.

Just upgrading a hint to an error – you see the CLI print out X errors – but still with an exit code of `0`.

**Comment by devoncarew** [comment]
@kevmoo, I believe this is addressed now. Closing this issue, but can you verify you see the fix?

**Comment by kevmoo** [comment]
Verified in 5d0056df884632451c58ba6f9aac47e891405444

(was still broken in 1.24.0-dev.2.0)

Did we add tests?

**Comment by devoncarew** [comment]
see  5d0056d
