### ISSUE TITLE
The getter 'fullName' was called on null.

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#29576]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA 171.4424.14`
- `1.24.0-edge.6b8a56cd7f1458e4d0cd5915a892982dd0f0d599`
- `IU-171.4424.14, JRE 1.8.0_112-release-736-b21x64 JetBrains s.r.o, OS Linux(amd64) v4.9.0-2-amd64 unknown, screens 3840x2160`

# Exception

Please append the contents of:
file:///tmp/report301.txt
[report301.txt](https://github.com/dart-lang/sdk/files/981769/report301.txt)

```
Dart analysis server, SDK version 1.24.0-edge.6b8a56cd7f1458e4d0cd5915a892982dd0f0d599, server version 1.18.0, error: Captured exception
NoSuchMethodError: The getter 'fullName' was called on null.
Receiver: null
Tried calling: fullName
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ChildDirectiveLinker.lookupFromLibrary (package:angular_analyzer_plugin/src/directive_linking.dart:231)
<asynchronous suspension>
#3      ChildDirectiveLinker.linkDirectives (package:angular_analyzer_plugin/src/directive_linking.dart:197)
<asynchronous suspension>
#4      AngularDriver.resolveDart (package:angular_analyzer_plugin/src/angular_driver.dart:598)
<asynchronous suspension>
#5      AngularDriver.pushDartErrors (package:angular_analyzer_plugin/src/angular_driver.dart:535)
<asynchronous suspension>
#6      AngularDriver.performWork (package:angular_analyzer_plugin/src/angular_driver.dart:232)
<asynchronous suspension>
#7      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#8      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#9      new AnalysisServer (package:analysis_server/src/analysis_server.dart:454)
#10     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:96)
#11     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:39)

**Comment by zoechi** [comment]
Looks like #29552

**Comment by bwilkerson** [comment]
@MichaelRFairhurst Can you confirm that this is fixed?

**Comment by MichaelRFairhurst** [comment]
This is not fixed. Its an issue with running our angular plugin on a codebase without angular

Ping @mk13 still plan to take this on?

**Comment by mk13** [comment]
Sure I'll take this on.

**Comment by mk13** [comment]
Hi @zoechi , we're trying to repro this issue but cannot accurately do so. Were you able to repro this issue consistently by doing a certain action on your IDE?

**Comment by zoechi** [comment]
Previously (#29552) I just restarted the analysis server from IntelliJ and while it reanalyzed the error occurred.
I could repeat this and it always behaved the same.
Currently (after some updates) I only got it once AFAIR (which led to creating this issue after I closed the other one recently).

**Comment by mk13** [comment]
Try patching with the recent plugin; we've implemented a quick fix for this issue: https://github.com/dart-lang/angular_analyzer_plugin/pull/311

Let me know if you see this same issue again or a similar issue.

**Comment by zoechi** [comment]
I haven't seen it since. Closing again. I'll reopen if I get it again.
