### ISSUE TITLE
Specification of `continue` behavior inside a switch statement makes no sense

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#30011]
The Dart language spec says:

> Let `s_c` be a `continue` statement. If `s_c` is of the form `continue L;`, then let `s_E` be the innermost labeled `do`, `for` or `while` statement or case clause with label `L` enclosing `s_c`.

But for the typical usage of `continue` within a switch statement, the target of the `continue` statement typically doesn't enclose `s_c`.  For example:

    switch (x) {
      case 0:
        ...
        continue foo; // s_c
      foo:
      case 1: // s_E (does not enclose s_c)
        ...
        break;
    }

If we took the spec literally, the target of a `continue` statement inside a switch would only be able to point to the originating case clause, which effectively allows turning a case clause into a loop.  I'm pretty sure that wasn't the intent.

I think the language should be adjusted to say something like this:

> Let `s_c` be a `continue` statement. If `s_c` is of the form `continue L;`, then let `s_E` be the innermost labeled `do`, `for` or `while` statement enclosing `s_c`, or the innermost or case clause with label `L` from a switch statement enclosing `s_c`.

...which allows continue expressions within switch statements to jump from one case clause to another.

I've verified that analyzer, dart2js, and the VM all behave consistently with the proposed spec change.

**Comment by kmillikin** [comment]
This seems like a duplicate of #23628.  It has been fixed in the spec in the repository.

**Comment by stereotype441** [comment]
I don't believe this bug has been fixed (nor has #23628).  The spec text in the repository still says:

> Let `s_c` be a `continue` statement. If `s_c` is of the form `continue L;`, then let `s_E` be the innermost labeled `do`, `for` or `while` statement or case clause with label `L` enclosing `s_c`.

(see https://github.com/dart-lang/sdk/blob/28084d1f8503404e9fdda3efa5b27bf441aa64d3/docs/language/dartLangSpec.tex#L6590)

**Comment by eernstg** [comment]
I looked into the spec too, and I agree that it still does not mention how continue works in a switch.

**Comment by kmillikin** [comment]
You are right.  I was misled because the duplicate had been closed.

**Comment by lrhn** [comment]
The runtime semantics are correct in the current specification, and doesn't rely on the "enclosing case clause", but the static warning still uses it. I'll reword that as well.
