### ISSUE TITLE
Postfix completion in string literals

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#30189]
![image](https://user-images.githubusercontent.com/384794/28337460-8ccc1046-6bba-11e7-8d2d-78fb66c6b7d5.png)

**Comment by stevemessick** [comment]
Need to get this fixed before 2017.3 is released.

**Comment by srawlins** [comment]
I think this is fixed. I don't see suggestions at that position.

**Comment by scheglov** [comment]
I still see it.
<img width="723" alt="image" src="https://user-images.githubusercontent.com/384794/162854717-2f9218ca-91e3-45ed-b744-96d4bf53e25c.png">
Here is the subset of the protocol:
```
1649723389997:Req:{"id"::"12823","method"::"completion.getSuggestions2","params"::{"file"::"/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/test/services/completion/dart/location/enum_test.dart","offset"::3954,"maxResults"::100,"completionCaseMatchingMode"::"FIRST_CHAR","completionMode"::"BASIC","invocationCount"::1},"clientRequestTime"::1649723389996}
1649723390048:Res:{"id"::"12823","result"::{"replacementOffset"::3954,"replacementLength"::0,"suggestions"::[],"isIncomplete"::false}}
1649723390052:Req:{"id"::"12824","method"::"edit.isPostfixCompletionApplicable","params"::{"file"::"/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/test/services/completion/dart/location/enum_test.dart","offset"::3953,"key"::".if"},"clientRequestTime"::1649723390052}
1649723390055:Res:{"id"::"12824","result"::{"value"::false}}
1649723390055:Req:{"id"::"12825","method"::"edit.isPostfixCompletionApplicable","params"::{"file"::"/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/test/services/completion/dart/location/enum_test.dart","offset"::3953,"key"::".return"},"clientRequestTime"::1649723390055}
1649723390057:Res:{"id"::"12825","result"::{"value"::true}}
1649723390057:Req:{"id"::"12826","method"::"edit.isPostfixCompletionApplicable","params"::{"file"::"/Users/scheglov/Source/Dart/sdk.git/sdk/pkg/analysis_server/test/services/completion/dart/location/enum_test.dart","offset"::3953,"key"::".while"},"clientRequestTime"::1649723390057}
1649723390060:Res:{"id"::"12826","result"::{"value"::false}}
```

**Comment by srawlins** [comment]
Oh whaaat, really? Maybe it is just not a bug in VS Code. Is this only when forcing the suggestions panel, with Ctrl+Space or something? I do see suggestions there.

**Comment by scheglov** [comment]
Maybe VS Code does not support postfix completion? Or does not support this bug :-)

**Comment by bwilkerson** [comment]
Postfix completion is an IntelliJ-only feature.

**Comment by srawlins** [comment]
Marked high priority as this suggests garbage in string literals, when postfix completion is enabled in IntelliJ, as we have many IntelliJ users.

**Comment by scheglov** [comment]
@jwren I still see it. DAS does not receive any request when I activate completion in a string.
<img width="1243" alt="image" src="https://github.com/dart-lang/sdk/assets/384794/e161ee05-28ce-4fd3-b96e-bd477dcc4864">

**Comment by bwilkerson** [comment]
If the Dart language server isn't getting completion requests, then I don't think there's anything we can do about it. Consider opening an issue on the JetBrains issue tracker.

**Comment by bwilkerson** [comment]
@jwren Is anyone triaging or fixing issues assigned to `area-intellij`?

**Comment by jwren** [comment]
Yes, thanks for the ping.  Yes, I do try to keep an eye on this label.

**Comment by Likhachev17** [comment]
any updates?
