### ISSUE TITLE
Dart Observatory bleeding edge is broken as a result of https://dart-review.googlesource.com/c/sdk/+/20664

### ISSUE THREAD

**Issue by efortuna** [dart-lang/sdk#31397]
Checking in this change: 
https://dart-review.googlesource.com/c/sdk/+/20664

Now causes Observatory to no longer work.

STEPS TO REPRO:
$ dart --observe  foo.dart

On opening the webpage, you will see a blank screen. If you open the console, the following error occurs:

Uncaught Error: NoSuchMethodError: method not found: 'json'
Receiver: ""
Arguments: []
   at Object.f (main.dart.js:2019)
   at Object.bx (main.dart.js:2203)
   at Object.a_r (main.dart.js:18371)
   at Vn.Bj (main.dart.js:19276)
   at Object.Qo (main.dart.js:15236)
   at B.S (main.dart.js:32759)
   at Object.J.z3 (main.dart.js:36452)
   at Ug.dart.aaa (main.dart.js:7688)
   at a3y.$0 (main.dart.js:2553)
   at pe.iU (main.dart.js:1524)

**Comment by floitschG** [comment]
Revert of the CL was rejected: https://dart-review.googlesource.com/c/sdk/+/21421

There was a test that had been modified in the meantime (`lib_2/convert/utf84_test.dart`) and reverting the CL would have broken the build.

I tried to upload my own revert, but my notebook is currently not set up for gerrit, and I'm unable to upload any change.

**Comment by lrhn** [comment]
Reverting just the changes to the observatory directory seems to be enough to fix the error, at least locally (https://dart-review.googlesource.com/c/sdk/+/21620).

This is probably just a garden variety bug, a variable renamed or not renamed incorrectly as part of the larger fix, that wasn't caught by any tests.

**Comment by lrhn** [comment]
Fixed by 84c8f27e51e8dba1d0f29fd823512033983d8003

**Comment by rakudrama** [comment]
Thanks for fixing Observatory.
I have been looking at the CL for quite a while and I still don't see why any of the s/JSON/json/ changes should have introduced an unresolved identifier, or introduced a reference to a local called 'json' ahead of the local's definintion.

**Comment by floitschG** [comment]
According to Zach, the observatory is not built with the latest SDK, but with the checked-in executable.
That would explain it (I think).

**Comment by lrhn** [comment]
That makes sense. In that case, *not* updating the code is the correct thing to do (until we decide to update the checked-in executable to Dart 2, but we only need to do that once).
