### ISSUE TITLE
"The getter 'element' was called on null" from analysis server

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#32327]
Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

I was editing the file below - I was typing of backspacing on the second to last line (where the `=>` is - I was typing the function syntax badly). I seem to be able to reproduce it semi-randomly be typing/removing characters around there.

```dart
// Before blank line

// After blank line

/// This is my class.
class MyClass {
  /// This is my num field.
  num myNumField;

  /// This is my num getter.
  int get myNumGetter => 1;

  /// This is my num setter.
  set myIntSetter(int value) {}

  /// This is my class constructor.
  MyClass();

  /// This is my class named constructor.
  MyClass.named();

  /// This is my void returning method.
  void myVoidReturningMethod() {}

  /// This is my string returning method.
  String myStringReturningMethod() {
    return "";
  }

  /// This is my method taking a string.
  void methodTakingString(String a) {}

  methodTakingFunction(Function(String) => )
}
```

### Versions

- Dart SDK 1.24.3
- Visual Studio Code 1.20.1
- Dart Code 2.9.0

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/danny/Dev/dart/latest/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.9.0
--preview-dart-2
```

### Exception

Analysis failed: /Users/danny/Dev/Dart-Code/test/test_projects/hello_world/lib/everything.dart context: exception_20180226_211052_835

```text
NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      TypeResolverVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:9902)
#3      GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5774)
#4      SimpleFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:9306)
#5      UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#6      TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10063)
#7      UnifyingAstVisitor.visitSimpleFormalParameter (package:analyzer/dart/ast/visitor.dart:3168)
#8      TypeResolverVisitor.visitSimpleFormalParameter (package:analyzer/src/generated/resolver.dart:10068)
#9      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:9301)
#10     DefaultFormalParameterImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3494)
#11     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#12     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10063)
#13     UnifyingAstVisitor.visitDefaultFormalParameter (package:analyzer/dart/ast/visitor.dart:2974)
#14     DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3490)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#16     FormalParameterListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4853)
#17     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#18     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10063)
#19     UnifyingAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:3020)
#20     ScopedVisitor.visitFormalParameterList (package:analyzer/src/generated/resolver.dart:7496)
#21     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4849)
#22     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7543)
#23     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#24     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10063)
#25     UnifyingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:3106)
#26     ScopedVisitor.visitMethodDeclarationInScope (package:analyzer/src/generated/resolver.dart:7728)
#27     ScopedVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:7720)
#28     TypeResolverVisitor.visitMethodDeclaration (package:analyzer/src/generated/resolver.dart:9911)
#29     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7535)
#30     TypeResolverVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:9764)
#31     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:7317)
#32     TypeResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:9710)
#33     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1923)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#35     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#36     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3121)
#37     TypeResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:10063)
#38     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#39     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#40     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:536)
#41     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:89)
#42     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#43     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:88)
#44     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:999)
#45     PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#46     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:987)
#47     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:834)
<asynchronous suspension>
#48     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1538)
<asynchronous suspension>
#49     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1481)
#50     new AnalysisServer (package:analysis_server/src/analysis_server.dart:458)
#51     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:89)
#52     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#53     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:474)
#54     _rootRun (dart:async/zone.dart:1120)
#55     _CustomZone.run (dart:async/zone.dart:1001)
#56     runZoned (dart:async/zone.dart:1467)
#57     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:513)
#58     Driver.start (package:analysis_server/src/server/driver.dart:473)
#59     main (file:///Users/whesse/dart/sdk/pkg/analysis_server/bin/server.dart:12)
#60     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by bwilkerson** [comment]
I believe that this was fixed by https://dart-review.googlesource.com/41922.

I noticed that it's reporting the version as "Dart SDK 1.24.3". That's really old; you might want to run a "2.0.0-dev" release.

**Comment by DanTup** [comment]
Oh wow, my bad! I still have the stable versions on my `PATH` and then send to switch on various projects - this was the first time I was editing Dart inside of the Dart Code codebase so it wasn't set. Thanks for pointing it out! =D
