### ISSUE TITLE
VM, package:vm_service_client and/or package:coverage fail to find source line/column

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/sdk#34841]
This is happening on Flutter commit https://github.com/flutter/flutter/commit/3fbd140e77601686acb336cd2af2838d03ba0572.

When we run tests with coverage, one of the tests fails with the following:

```
/b/build/slave/Linux/build/flutter/packages/flutter/test/widgets/binding_test.dart
Bad state: Couldn't find line and column for token 3230 in file:///b/build/slave/Linux/build/flutter/packages/flutter/lib/src/widgets/binding.dart.
#0      VMScript._lineAndColumn (package:vm_service_client/src/script.dart:243:5)
#1      _ScriptLocation._ensureLineAndColumn (package:vm_service_client/src/script.dart:314:26)
#2      _ScriptLocation.line (package:vm_service_client/src/script.dart:295:5)
#3      _getCoverageJson (package:coverage/src/collect.dart:103:46)
<asynchronous suspension>
#4      _getAllCoverage (package:coverage/src/collect.dart:51:26)
<asynchronous suspension>
#5      collect (package:coverage/src/collect.dart:35:18)
<asynchronous suspension>
#6      CoverageCollector.collectCoverage (package:flutter_tools/src/test/coverage_collector.dart:55:45)
<asynchronous suspension>
#7      CoverageCollector.handleFinishedTest (package:flutter_tools/src/test/coverage_collector.dart:27:11)
<asynchronous suspension>
#8      _FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:649:30)
<asynchronous suspension>
#9      _FlutterPlatform.loadChannel (package:flutter_tools/src/test/flutter_platform.dart:408:36)
#10     PlatformPlugin.load (package:test/src/runner/plugin/platform.dart:65:19)
<asynchronous suspension>
#11     Loader.loadFile.<anonymous closure> (package:test/src/runner/loader.dart:245:36)
<asynchronous suspension>
#12     new LoadSuite.<anonymous closure>.<anonymous closure> (package:test/src/runner/load_suite.dart:92:31)
<asynchronous suspension>
#13     invoke (package:test/src/utils.dart:241:5)
#14     new LoadSuite.<anonymous closure> (package:test/src/runner/load_suite.dart:91:7)
#15     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
<asynchronous suspension>
#16     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#17     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#18     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#19     _rootRun (dart:async/zone.dart:1120:38)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#23     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#24     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#28     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#29     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#30     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#31     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

[Full log file](https://build.chromium.org/p/client.flutter/builders/Linux/builds/6966/steps/run%20test.dart%20for%20coverage%20shard/logs/stdio).

/cc @JekCharlsonYu @a-siva @cbracken

**Comment by cbracken** [comment]
Potentially relevant issue from when something similar came up last time:
dart-lang/coverage#194

I'd banged up dart-lang/coverage#216 at the time, but I didn't land it; I suspect because perhaps it didn't solve the issue.

**Comment by yjbanov** [comment]
Some more info: the vm_service_client is looking for token 3230 but seems to be receiving the following `tokenPosTable` from the VM:

```
  245, 8164, 3, 8165, 4
  246, 8181, 8, 8194, 21
  247, 8209, 11
  248, 8230, 5
  249, 8252, 5, 8263, 16, 8282, 35
  250, 8312, 8, 8319, 15, 8337, 33
  251, 8365, 8, 8372, 15, 8405, 48
  252, 8460, 20, 8471, 31, 8492, 52
  253, 8541, 20, 8548, 27, 8566, 45
  254, 8591, 3
  261, 8870, 3, 8896, 29, 8905, 38, 8908, 41, 8917, 50
  262, 8943, 25
  264, 8957, 3, 8958, 4
  265, 8974, 8, 8995, 29
  266, 9010, 11
  268, 9051, 16, 9065, 30, 9072, 37
  269, 9112, 5, 9117, 10
  270, 9140, 7
  272, 9220, 19
  273, 9235, 11
  274, 9261, 11, 9268, 18
  275, 9293, 10
  278, 9311, 7
  280, 9397, 17, 9400, 20
  281, 9411, 9, 9441, 39, 9472, 70
  282, 9490, 17, 9496, 23
  283, 9515, 11, 9530, 26, 9561, 57, 9564, 60
  284, 9583, 13
  285, 9633, 22, 9666, 55
  286, 9683, 11, 9690, 18
  287, 9716, 10
  291, 9745, 12
  292, 9756, 7
  294, 9836, 17, 9839, 20, 9842, 23, 9872, 53, 9897, 78
  295, 9915, 17, 9921, 23
  296, 9940, 11, 9955, 26, 9980, 51, 9983, 54
  297, 10002, 13
  298, 10052, 22, 10079, 49
  299, 10096, 11, 10103, 18
  300, 10129, 10
  304, 10221, 7
  306, 10304, 17, 10316, 29, 10341, 54
  307, 10359, 17, 10365, 23, 10378, 36
  308, 10390, 11, 10394, 15, 10420, 41, 10423, 44
  309, 10442, 13, 10470, 41
  310, 10486, 10
  313, 10527, 30, 10536, 39, 10558, 61
  315, 10592, 7
  316, 10610, 6, 10612, 8
  317, 10617, 3
  319, 10622, 3, 10635, 16, 10648, 29
  320, 10657, 5, 10661, 9, 10679, 27
  321, 10696, 7, 10707, 18, 10718, 29
  322, 10744, 7, 10751, 14
  324, 10773, 5
  325, 10804, 3
  329, 10924, 3, 10939, 18, 10950, 29, 10953, 32, 10964, 43
  330, 10985, 20, 10999, 34
  338, 11250, 3, 11267, 20, 11280, 33, 11283, 36, 11295, 48, 11307, 60
  340, 11347, 38, 11384, 75
  359, 12291, 3, 12296, 8, 12307, 19, 12331, 43, 12344, 56, 12355, 67, 12359, 71, 12368, 80
  369, 12714, 3, 12719, 8, 12733, 22, 12757, 46, 12770, 59, 12781, 70, 12788, 77, 12797, 86
  371, 12802, 3, 12803, 4
  372, 12819, 8, 12839, 28
  373, 12854, 11
  374, 12882, 5, 12910, 33, 12922, 45
  375, 12940, 7, 12949, 16
  376, 12971, 3
  378, 12976, 3, 12977, 4
  379, 12993, 8, 13021, 36
  380, 13036, 11
  381, 13072, 5, 13100, 33, 13112, 45
  382, 13130, 7, 13139, 16
  383, 13169, 3
  385, 13174, 3, 13175, 4
  386, 13191, 8, 13225, 42
  387, 13240, 11
  388, 13282, 5, 13310, 33, 13322, 45
  389, 13340, 7, 13349, 16
  390, 13385, 3
  397, 13552, 3, 13553, 4
  398, 13566, 4
  399, 13587, 8, 13606, 27
  400, 13615, 5, 13640, 30, 13647, 37
  401, 13658, 3
  409, 13937, 3, 13938, 4
  410, 13951, 4
  411, 13972, 8, 13993, 29, 14001, 37
  412, 14015, 5, 14043, 33, 14055, 45
  413, 14073, 7, 14082, 16, 14098, 32
  414, 14109, 3
  422, 14466, 3, 14467, 4
  423, 14480, 4
  424, 14501, 8, 14537, 44
  425, 14546, 5, 14574, 33, 14586, 45
  426, 14604, 7, 14613, 16
  427, 14649, 3
  443, 15314, 3, 15315, 4
  444, 15340, 16, 15354, 30, 15363, 39
  445, 15369, 5, 15397, 33, 15406, 42, 15443, 79
  446, 15464, 7, 15468, 11, 15474, 17, 15483, 26
  447, 15506, 9
  449, 15540, 21
  450, 15549, 3
  462, 16024, 3, 16025, 4
  463, 16038, 4
  464, 16067, 16, 16082, 31, 16090, 39, 16103, 52
  465, 16109, 5, 16137, 33, 16146, 42, 16183, 79
  466, 16204, 7, 16208, 11, 16214, 17, 16223, 26, 16236, 39
  467, 16252, 9
  469, 16268, 3
  471, 16273, 3, 16289, 19, 16316, 46, 16328, 58
  472, 16346, 5, 16354, 13, 16365, 24
  473, 16386, 12
  474, 16406, 9, 16413, 16
  475, 16442, 12
  476, 16463, 9, 16470, 16, 16486, 32, 16497, 43
  478, 16519, 5
  479, 16553, 3
  481, 16558, 3, 16559, 4
  482, 16575, 8, 16605, 38, 16624, 57
  483, 16643, 11, 16674, 42
  484, 16686, 5, 16714, 33, 16726, 45
  485, 16744, 7, 16753, 16, 16780, 43
  486, 16790, 3
  496, 17098, 3, 17103, 8, 17123, 28
  497, 17132, 5, 17160, 33, 17172, 45
  498, 17190, 7, 17199, 16
  499, 17226, 3
  501, 17231, 3, 17244, 16, 17264, 36, 17272, 44, 17293, 65
  502, 17326, 32, 17334, 40, 17336, 42
  503, 17368, 18, 17373, 23, 17375, 25, 17382, 32
  504, 17396, 5, 17404, 13
  505, 17423, 12
  506, 17449, 9
  507, 17481, 9
  509, 17498, 5
  510, 17508, 3
  512, 17518, 8
  513, 17556, 7
  514, 17591, 3, 17600, 12, 17618, 30, 17621, 33, 17649, 61, 17653, 65
  523, 17958, 3, 17967, 12, 17995, 40, 17998, 43, 17999, 44, 18022, 67
  531, 18342, 3, 18347, 8, 18368, 29
  532, 18384, 12, 18412, 40, 18416, 44
  533, 18423, 5, 18451, 33
  534, 18459, 3
  545, 18865, 3, 18870, 8, 18891, 29
  546, 18907, 12, 18935, 40, 18939, 44
  547, 18946, 5, 18974, 33
  548, 18982, 3
  550, 18987, 3, 18992, 8, 19013, 29
  553, 19140, 12
  554, 19151, 7, 19155, 11
  555, 19193, 9, 19199, 15
  573, 20285, 7
  574, 20303, 6, 20305, 8
  575, 20312, 5
  576, 20336, 3
  584, 20576, 4
  585, 20593, 8
  651, 23826, 3, 23827, 4
  652, 23843, 8, 23852, 17
  653, 23868, 12, 23869, 13, 23895, 39
  654, 23909, 12
  655, 23920, 7
  656, 23961, 7
  657, 23979, 6, 23981, 8
  659, 24000, 7, 24004, 11, 24022, 29
  660, 24039, 9, 24050, 20, 24061, 31
  661, 24093, 13
  662, 24112, 7, 24123, 18
  664, 24168, 14
  665, 24181, 9
  666, 24225, 9
  667, 24245, 8, 24247, 10
  671, 24421, 5, 24425, 9, 24452, 36
  672, 24498, 26
  673, 24557, 7, 24616, 66
  674, 24627, 7
  676, 24668, 3
  682, 24885, 3, 24897, 15, 24915, 33, 24918, 36, 24936, 54
  683, 24948, 11
  691, 25208, 3, 25213, 8, 25229, 24, 25237, 32
  692, 25255, 5, 25276, 26
  693, 25333, 18
  695, 25397, 14
  696, 25414, 7, 25433, 26, 25445, 38
  697, 25467, 3
  699, 25472, 3, 25473, 4
  700, 25497, 16, 25514, 33
  701, 25523, 5
  702, 25552, 5, 25556, 9, 25574, 27
  703, 25589, 7, 25600, 18, 25611, 29
  704, 25635, 5, 25648, 18, 25668, 38, 25673, 43, 25679, 49
  705, 25694, 7
  706, 25724, 6
  707, 25729, 3
```

**Comment by yjbanov** [comment]
That table is for this file: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/binding.dart

Notice that the first line coincides with a `mixin` declaration, so it might be mixin-related. @kmillikin

**Comment by a-siva** [comment]
Similar errors were reported from the Flutter buildbot when an attempt was made to roll Dart version `ac6d4f7e653deba11d4836768376537893a9e9d6` into Flutter (this roll was reverted because of this).

Please see [link](https://build.chromium.org/p/client.flutter/builders/Linux/builds/6951/steps/run%20test.dart%20for%20coverage%20shard/logs/stdio) for details.

Here is an extract from that buildbot output file
```
2:28 +325 -2: /b/build/slave/Linux/build/flutter/packages/flutter/test/cupertino/nav_bar_transition_test.dart: Bottom large title moves to top back label                                             
02:31 +325 -2: /b/build/slave/Linux/build/flutter/packages/flutter/test/cupertino/nav_bar_transition_test.dart: Bottom large title moves to top back label                                             
02:33 +326 -2: /b/build/slave/Linux/build/flutter/packages/flutter/test/cupertino/nav_bar_transition_test.dart: Bottom large title moves to top back label                                             
unhandled error during test:
/b/build/slave/Linux/build/flutter/packages/flutter/test/cupertino/dialog_test.dart
Bad state: Couldn't find line and column for token 135177 in org-dartlang-sdk:///flutter/lib/ui/painting.dart.
#0      VMScript._lineAndColumn (package:vm_service_client/src/script.dart:243:5)
#1      _ScriptLocation._ensureLineAndColumn (package:vm_service_client/src/script.dart:314:26)
#2      _ScriptLocation.line (package:vm_service_client/src/script.dart:295:5)
#3      _getCoverageJson (package:coverage/src/collect.dart:103:46)
<asynchronous suspension>
#4      _getAllCoverage (package:coverage/src/collect.dart:51:26)
<asynchronous suspension>
#5      collect (package:coverage/src/collect.dart:35:18)
<asynchronous suspension>
#6      CoverageCollector.collectCoverage (package:flutter_tools/src/test/coverage_collector.dart:55:45)
<asynchronous suspension>
#7      CoverageCollector.handleFinishedTest (package:flutter_tools/src/test/coverage_collector.dart:27:11)
<asynchronous suspension>
#8      _FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:649:30)
<asynchronous suspension>
#9      _FlutterPlatform.loadChannel (package:flutter_tools/src/test/flutter_platform.dart:408:36)
#10     PlatformPlugin.load (package:test/src/runner/plugin/platform.dart:65:19)
<asynchronous suspension>
#11     Loader.loadFile.<anonymous closure> (package:test/src/runner/loader.dart:245:36)
<asynchronous suspension>
#12     new LoadSuite.<anonymous closure>.<anonymous closure> (package:test/src/runner/load_suite.dart:92:31)
<asynchronous suspension>
#13     invoke (package:test/src/utils.dart:241:5)
#14     new LoadSuite.<anonymous closure> (package:test/src/runner/load_suite.dart:91:7)
#15     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
<asynchronous suspension>
#16     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#17     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#18     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#19     _rootRun (dart:async/zone.dart:1120:38)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#23     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#24     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#28     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#29     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#30     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
```

I am trying to reproduce this failure with a local engine build in order to bisect the Dart changes but unfortunately I can't get it to fail with a local engine build.

**Comment by aartbik** [comment]
@aartbik for dart roll

**Comment by yjbanov** [comment]
Should someone be assigned to work on this asap? This is a TODAY issue in Flutter https://github.com/flutter/flutter/issues/23225.

**Comment by a-siva** [comment]
Disabling this new option 'unsafePackageSerialization' fixes the problem. I am going to upload CL that flips this to false.
This flag was added here  https://github.com/flutter/flutter/commit/4bd6ad73954e42a98003a6e23502df0487ff5dfd#diff-39538134dff328da5360691916bf0f06

**Comment by a-siva** [comment]
[flutter/pull/23280](https://github.com/flutter/flutter/pull/23280) has been created for this.

**Comment by jensjoha** [comment]
Here's what's happening:

When unsafe package serialization is enabled, the VM is given a concatenated dill file.

In this case, 3 scripts are created in the VM for the same absolute file.
One for the actual library, and 2 - I guess - for two separate mixin uses.
The reason we get 3 different ones instead of just 1, is because each live in a separate component inside the concatenated dill file.

One of them gets the url set as the import-url, the two others are kept as is, so we now have:
- package:flutter/src/widgets/binding.dart (this script is attached to the library where the entire thing is compiled)
- file:///[...]/flutter/packages/flutter/lib/src/widgets/binding.dart (this script is attached to a class and/or number of methods because of a mixin usage) (mixin WidgetsBinding, lines 244-708))
- file:///[...]/flutter/packages/flutter/lib/src/widgets/binding.dart (this script is attached to a class and/or number of methods because of a mixin usage) (abstract class WidgetsBindingObserver, lines 78-241)

When asking for the SourceReport, the VM assumes that if two scripts urls are the same, the scripts are the same too (in the above that is not the case --- this cannot be assumed when supporting concatenated dill files) and reuses an existing (wrong) one, i.e. giving responsibility for both scripts to one of the scripts.
When asking that script for which token positions it has, it reports the ones it is responsible for --- it doesn't know about the other script(s).

The data given from the VM is something like:

```
URI: package:flutter/src/widgets/binding.dart
ID: libraries/@616399801/scripts/package%3Aflutter%2Fsrc%2Fwidgets%2Fbinding.dart/1668b94849e
[78, 2484, 1]
[94, 3230, 3, 3243, 16, 3254, 27, 3257, 30, 3260, 33, 3285, 58]
[...]
[945, 34099, 3]

URI: file:///[...]/flutter/packages/flutter/lib/src/widgets/binding.dart
ID: objects/26
[245, 8164, 3, 8165, 4]
[246, 8181, 8, 8194, 21]
[...]
[707, 25729, 3]
```
Note how there are only two outputs.

Solution: Don't think Scripts are the same based on their url. Not in the VM, and not in any application of the service protocol.

With my CL (https://dart-review.googlesource.com/80821) applied the answer from the VM is now:
```
URI: package:flutter/src/widgets/binding.dart
ID: libraries/@616399801/scripts/package%3Aflutter%2Fsrc%2Fwidgets%2Fbinding.dart/1668befc930
[78, 2484, 1]
[94, 3230, 3, 3243, 16, 3254, 27, 3257, 30, 3260, 33, 3285, 58]
[...]
[945, 34099, 3]

URI: file:///[...]/flutter/packages/flutter/lib/src/widgets/binding.dart
ID: objects/56
[245, 8164, 3, 8165, 4]
[246, 8181, 8, 8194, 21]
[...]
[707, 25729, 3]

URI: file:///[...]/flutter/packages/flutter/lib/src/widgets/binding.dart
ID: objects/57
[94, 3230, 3, 3243, 16, 3254, 27, 3257, 30, 3260, 33, 3285, 58]
[...]
[240, 7948, 3, 7953, 8, 7983, 38, 7987, 42]
```
We now have 3 outputs.

Patching in https://github.com/dart-lang/coverage/pull/216 (thanks @cbracken) in [...]/.pub-cache/hosted/pub.dartlang.org/coverage-0.12.2/lib/src/collect.dart and running flutter with my patched VM everything seems to work (`19:44 +3172 ~23: All tests passed!`).

So while disabling unsafe package serialization does work that's hardly a good solution, and it more masks the problem than fixes it.

**Comment by jensjoha** [comment]
Oh, and also, probably one doesn't have to do a lot of hot-reloading before the assumption about one script per url goes out the window...

**Comment by dgrove** [comment]
Is this still targeted for 2.1?

**Comment by cbracken** [comment]
I've now landed my patch in the coverage package.

**Comment by a-siva** [comment]
Flutter is unblocked with unsafePackageSerialization being turned off, moving milestore to 2.2 and dropping priority to P2

**Comment by zoechi** [comment]
I'm still seeing this 
```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.1 18B75, locale en-AT)
```
like explained in https://github.com/flutter/flutter/issues/20811

**Comment by jensjoha** [comment]
With the reproduction from the flutter issue link - further boiled down to this:
`t1.dart`:
```
// this is a somewhat long line that pushes offsets and bytes
// this is a somewhat long line that pushes offsets and bytes
// this is a somewhat long line that pushes offsets and bytes
// this is a somewhat long line that pushes offsets and bytes
// this is a somewhat long line that pushes offsets and bytes
// this is a somewhat long line that pushes offsets and bytes
// this is a somewhat long line that pushes offsets and bytes
// this is a somewhat long line that pushes offsets and bytes
// this is a somewhat long line that pushes offsets and bytes
// this is a somewhat long line that pushes offsets and bytes

import "t2.dart";

class Bar extends Object with Foo { }

main() {
  Bar bar = new Bar();
  print(bar.foo);
}
```

`t2.dart`:
```
class Foo {
  final String foo = () {
    return StackTrace.current.toString().split("\n")[0];
  }();
}
```

(which has the added benefit of showing something wrong when running)

 this is what's happening:
* The mixin causes fasta to create an artificial class, `abstract class _Bar&Object&Foo extends core::Object implements t2::Foo`
* This class has the field (`foo` in this case, `firstNameValidation` in the example from the flutter link) copied in. This field comes from a different file and is correctly marked as such in the dill file (`t2.dart` in this example, whereas the artificial class is created in the library created by `t1.dart`).
* The VM basically initializes fields by copying the initializer-code into the constructor and assigning the result of it to the field. The constructor is marked as coming from `t1.dart` in this example. From the VMs perspective, the fields initializer code (originally from `t2.dart`) now comes from `t1.dart` instead.
* The output of the program is thus wrong because the VM translates the offsets relative to the wrong file (`#0      new _Bar&Object&Foo.<anonymous closure> ([...]/t1.dart:1:61)`).
* When doing coverage on it we get the error (`Bad state: Couldn't find line and column for token 33 in [...]/t1.dart.`) (the error makes sense --- token 33 is somewhere in the comment on the first line in t1.dart --- had it looked for it in t2.dart instead (as the VM *should* have instructed it) it would have found something that made sense.

One solution is to mark the constructor as coming from `t2.dart` (in this example) - but I don't know if that's the way to go. Maybe @peter-ahe-google has an opinion about that?

**Comment by jensjoha** [comment]
I'm landing a test that demonstrates the problem (https://dart-review.googlesource.com/c/sdk/+/91660), but the frontend team doesn't find that this is a frontend issue - it's a VM issue, and it should be fixed in the VM. Unassigning and changing area-label.

**Comment by a-siva** [comment]
This is fixed by the following CLs
https://dart-review.googlesource.com/c/sdk/+/97104
https://dart-review.googlesource.com/c/sdk/+/97402

**Comment by ZichangG** [comment]
This issue still exists. The mixin class has not been fixed.

**Comment by dgrove** [comment]
I don't believe this is required for 2.3 . If not, can you please move from milestone?

**Comment by dgrove** [comment]
This is not blocking 2.3 - removing from milestone.
