### ISSUE TITLE
dart2js should support assert(x == null || x >= 0.0) in initializer lists

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/sdk#35801]
Consider the following code:

```dart
class A {
  const A({this.x}) : assert(x == null || x >= 0.0);
  final double x;
}

main() {
  print(const A());
}
```

If you try to compile this with dart2js, you will get:

```
Error: `null` of type 'Null' is not a valid operand of a constant binary >= expression. Must be a value of type 'int' or 'double'.
  var a = const A();
                ^
```

The VM can run this code. dart2js should be smarter and realize that the `x == null` case has already been guarded against.

**Comment by hterkelsen** [comment]
The `Align` class from Flutter is an example of a class using this kind of assert in its initializer list:
https://github.com/flutter/flutter/blob/ef276ffea501a9f9ea4d627f9d069e52a31b75be/packages/flutter/lib/src/widgets/basic.dart#L1540

**Comment by yjbanov** [comment]
This is now blocking integration of `dart2js` into the Flutter SDK.

**Comment by sigmundch** [comment]
We are in the process of swapping to the CFE's constant evaluation in dart2js, so I wonder if this should be fixed directly there (if it isn't already) rather than putting the time to fix it in our soon to be deprecated constant evaluation logic.

**Comment by yjbanov** [comment]
What's the status of this issue? As of https://github.com/dart-lang/sdk/commit/0f9a5198bd644e908adcf8061e6a9722a40a2f93 (a today's revision) `flutter build web` still crashes on const asserts.

**Comment by sigmundch** [comment]
Work started, but my guess ETA is a few weeks. In particular, to avoid throw away work, we are taking the route of replacing our constant evaluation first with the CFE constant evaluation. Currently that requires a few pieces of work, including:
* Conversion of CFE constants to dart2js constants
* Adding JS-specific constant evaluation logic to the CFE

If this timeline is too long, let us know so we can evaluate whether we should add support for this to our old constant evaluator.

**Comment by sigmundch** [comment]
I took a closer look and adding support directly appears to be a pretty small change, so we might do that first to unblock you.

**Comment by yjbanov** [comment]
Cool! Thanks. For Flutter Web specifically it would even be OK to just strip out the asserts. We will temporarily lose some checking, but it won't break correct code, which matters more than breaking incorrect code.

**Comment by rakudrama** [comment]
That is what I was thinking - we could just ignore const asserts with the assumption they are checked by the CFE in the nearish future.

**Comment by sigmundch** [comment]
Oh, interesting idea. The fix I landed does the short-circuiting on logical binary operators instead: 82a15835f06b01912fe092f7a74ff24cec4cf5f9

I believe this just takes us a step closer without breaking any existing code.

> ..., which matters more than breaking incorrect code.

@yjbanov - Not sure what you meant here, what do you mean by `breaking incorrect code`?

**Comment by yjbanov** [comment]
@sigmundch 

Incorrect code is expected to fail the assertion. If we ignore const asserts then it won't fail, meaning we broke the incorrect code. However, this will not be important in the next few weeks. We'd be ok with taking this regression in exchange for being able to compile the code at all.
