### ISSUE TITLE
http.MultipartRequest don‘t post field array to server？

### ISSUE THREAD

**Issue by davewang** [dart-lang/sdk#35836]
http.MultipartRequest don‘t post field array to server？
I have request post field array to server is can't do？

**Comment by a-siva** [comment]
Could you explain the context of this question with some more details, e.g: some sample code

**Comment by davewang** [comment]
https://github.com/dart-lang/http/blob/7df1d6942fbfdf8ffdf8cfeebeadb97e3898afa2/test/multipart_test.dart#L32

e.g 
` request.fields['tags'] = 'foo';   request.fields['tags'] = 'bar';`

But now ,I fixed it myself.

**Comment by vsmenon** [comment]
Is there still an issue?  If so, please open on the `http` package:

https://github.com/dart-lang/http/issues
