### ISSUE TITLE
GPG error: The following signatures were invalid

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/sdk#36620]
Looks like a user was having trouble [installing Dart on Linux](https://webdev.dartlang.org/guides/get-started#2-install-dart).

From https://github.com/dart-lang/angular/issues/1788:

> Hi, I am trying to install angulardart from https://webdev.dartlang.org/guides/get-started (step 2), but 'sudo apt-get update' results in the following and I am unable to install :
>
> W: GPG error: https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release: The following signatures were invalid: EXPKEYSIG 1397BC53640DB551 Google Inc. (Linux Packages Signing Authority) linux-packages-keymaster@google.com
E: The repository 'https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by leonsenft** [comment]
@geniusunil

**Comment by Admiralfeb** [comment]
Looks like Chrome had the same problem as the key expired and they had to re-sign the repository. https://support.google.com/chrome/thread/4032170

**Comment by athomas** [comment]
This is fixed.

See also https://github.com/dart-lang/site-www/issues/1457

**Comment by marc1091** [comment]
I am still getting the  same  error 

An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release: The following signatures were invalid: EXPKEYSIG 1397BC53640DB551 Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com>Failed to fetch https://storage.googleapis.com/download.dartlang.org/linux/debian/dists/stable/Release.gpg  The following signatures were invalid: EXPKEYSIG 1397BC53640DB551 Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com>Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by athomas** [comment]
I've tried to reproduce this on a clean install, but I don't get any errors.

I've also verified the keys in the storage buckets aren't signed with the new old key anymore:
```
$ wget https://storage.googleapis.com/download.dartlang.org/linux/debian/dists/stable/Release.gpg
$ wget https://storage.googleapis.com/download.dartlang.org/linux/debian/dists/stable/Release
$ wget https://dl-ssl.google.com/linux/linux_signing_key.pub
$ gpg --import linux_signing_key.pub
$ gpg --verify Release.gpg Release
gpg: Signature made Mon Apr 15 14:36:51 2019 UTC
gpg:                using RSA key 6494C6D6997C215E
gpg: Good signature from "Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com>" [unknown]
...

Do the steps listed here help?
https://linux-audit.com/how-to-solve-an-expired-key-keyexpired-with-apt/

**Comment by Admiralfeb** [comment]
I'm on Ubuntu 18.10. I've tried adding the new key as well as removing the apt repository and readding it (both by .deb file and the installation instructions). I'm still getting the issue.

**Comment by alescdb** [comment]
Same for me :
```
Ign:22 https://storage.googleapis.com/download.dartlang.org/linux/debian stable InRelease
Ign:23 https://storage.googleapis.com/download.dartlang.org/linux/debian unstable InRelease
Hit:24 https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release
Hit:25 https://storage.googleapis.com/download.dartlang.org/linux/debian unstable Release
Err:27 https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release.gpg
  The following signatures were invalid: EXPKEYSIG 1397BC53640DB551 Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com>
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release: The following signatures were invalid: EXPKEYSIG 1397BC53640DB551 Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com>
W: Failed to fetch https://storage.googleapis.com/download.dartlang.org/linux/debian/dists/stable/Release.gpg  The following signatures were invalid: EXPKEYSIG 1397BC53640DB551 Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com>
```

**Comment by tpv-ebben** [comment]
I was also having the issue after following the linked steps in Ubuntu 18.10. What fixed it for me was: 

```bash
mv /etc/apt/sources.list.d/dart_stable.list /etc/apt/sources.list.d/dart_stable.disabled
apt update
mv /etc/apt/sources.list.d/dart_stable.disabled /etc/apt/sources.list.d/dart_stable.list
apt update
```

**Comment by Petrox** [comment]
> I was also having the issue after following the linked steps in Ubuntu 18.10. What fixed it for me was:
> 
> ```shell
> mv /etc/apt/sources.list.d/dart_stable.list /etc/apt/sources.list.d/dart_stable.disabled
> apt update
> mv /etc/apt/sources.list.d/dart_stable.disabled /etc/apt/sources.list.d/dart_stable.list
> apt update
> ```

In theory this should not work. But it does.

**Comment by jeffnst** [comment]
> I was also having the issue after following the linked steps in Ubuntu 18.10. What fixed it for me was:
> 
> ```shell
> mv /etc/apt/sources.list.d/dart_stable.list /etc/apt/sources.list.d/dart_stable.disabled
> apt update
> mv /etc/apt/sources.list.d/dart_stable.disabled /etc/apt/sources.list.d/dart_stable.list
> apt update
> ```

this work for me, ubuntu 18.04 ... tq

**Comment by athomas** [comment]
The Chromium team informed me that this may be caused by not updating the Release file. I've now updated the "Date" header in the Release file, and uploaded new Release & Release.gpg files.

The workarounds should no longer be necessary.

**Comment by Admiralfeb** [comment]
Just ran `sudo apt update` on Ubuntu 19.04 and no issues with dartlang now. Thanks
