### ISSUE TITLE
lib_2/mirrors/invocation_fuzz_test/emptyarray fails on Mac Product

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/sdk#37680]
https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8906421057139188768/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0

The failure appears to be caused by `fe2f8265` or `59aa4cd6`.

**Comment by mkustermann** [comment]
@sjindel-google Did you investigate why the VM segfaults?

**Comment by sjindel-google** [comment]
I didn't recognize the segfault due to the absence of a stack trace -- I thought it was a normal error. I'll take a look.

**Comment by mkustermann** [comment]
(the flakiness dashboard as well as the failure mention it's a Crash)

**Comment by rmacnak-google** [comment]
Likely fixed by https://dart-review.googlesource.com/c/sdk/+/110620

**Comment by sjindel-google** [comment]
BigQuery and the flakiness dashboard form that the test is still crashing flakily.

**Comment by sjindel-google** [comment]
This appears to be the same cause as https://github.com/dart-lang/sdk/issues/37780, the original fix was not complete. I've uploaded https://dart-review.googlesource.com/c/sdk/+/114861 to address it.
