### ISSUE TITLE
Analyzer crash: type 'BlockFunctionBodyImpl' is not a subtype of type 'TypeAnnotation'

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#38674]
My analyzer keeps crashing.

Version: latest commit from master: https://github.com/dart-lang/sdk/commit/470c5eab8ea8c456152ceb04cb7e52aeb29a7ca5

Logs from VSCode.

```
[5:08:04 PM] [General] [Info] Done!
[5:08:04 PM] [General] [Info] Analyzer:Startup timing: 676ms
[5:08:59 PM] [Analyzer] [Error] Captured exception
[5:08:59 PM] [Analyzer] [Error] type 'BlockFunctionBodyImpl' is not a subtype of type 'TypeAnnotation'
#0      AstBuilder.endExtensionDeclaration (package:analyzer/src/fasta/ast_builder.dart:828:20)
#1      Parser.parseExtension (package:front_end/src/fasta/parser/parser.dart:2144:14)
#2      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:614:18)
#3      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#4      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#5      ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:159:32)
#6      ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:154:12)
#7      _File._parse (package:analyzer/src/services/available_declarations.dart:1842:23)
#8      _File.refresh (package:analyzer/src/services/available_declarations.dart:1163:30)
#9      DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:660:14)
#10     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:573:18)
#11     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:281:13)
#12     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#13     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:280:27)
#14     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
#15     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:…
[5:08:59 PM] [Analyzer] [Error] Captured exception
[5:08:59 PM] [Analyzer] [Error] type 'BlockFunctionBodyImpl' is not a subtype of type 'TypeAnnotation'
#0      AstBuilder.endExtensionDeclaration (package:analyzer/src/fasta/ast_builder.dart:828:20)
#1      Parser.parseExtension (package:front_end/src/fasta/parser/parser.dart:2144:14)
#2      Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:614:18)
#3      Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:468:14)
#4      Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:350:15)
#5      ParserAdapter.parseCompilationUnit2 (package:analyzer/src/generated/parser_fasta.dart:159:32)
#6      ParserAdapter.parseCompilationUnit (package:analyzer/src/generated/parser_fasta.dart:154:12)
#7      _File._parse (package:analyzer/src/services/available_declarations.dart:1842:23)
#8      _File.refresh (package:analyzer/src/services/available_declarations.dart:1163:30)
#9      DeclarationsTracker._getFileByPath (package:analyzer/src/services/available_declarations.dart:660:14)
#10     DeclarationsTracker.doWork (package:analyzer/src/services/available_declarations.dart:573:18)
#11     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:281:13)
#12     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#13     CompletionLibrariesWorker.performWork (package:analysis_server/src/domains/completion/available_suggestions.dart:280:27)
#14     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1901:35)
#15     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:…
[5:08:59 PM] [Analyzer] [Error] Captured exception
[5:08:59 PM] [Analyzer] [Error] type 'BlockFunctionBodyImpl' is not a subtype of type 'TypeAnnotation'
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:673:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      Future._propagateToListeners (dart:async/future_impl.dart:594:16)
#3      Future._completeError (dart:async/future_impl.dart:530:5)
#4      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:578:7)
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
[5:08:59 PM] [Analyzer] [Error] Unhandled exception:
type 'BlockFunctionBodyImpl' is not a subtype of type 'TypeAnnotation'
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:673:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Logs from command line (kinda looks like a different error):

```
$ dartanalyzer ./
Analyzing sdk...
Unhandled exception:
_ElementMismatchException: Element mismatch in /usr/local/google/home/dacoharkes/dart-sdk/sdk/pkg/front_end/testcases/general/having_part_with_parts_and_annotation_lib1.dart at /usr/local/google/home/dacoharkes/dart-sdk/sdk/pkg/front_end/testcases/general/having_part_with_parts_and_annotation_lib1.dart
Caused by RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core-patch/growable_array.dart:147:60)
#1      DeclarationResolver.visitPartDirective (package:analyzer/src/generated/declaration_resolver.dart:384:50)
#2      PartDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052:49)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#4      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2160:19)
#5      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:725:10)
#6      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#7      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:43:12)
#8      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:641:31)
#9      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:151:7)
#10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#11     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:150:11)
#12     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:113:14)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:112:43)
#15     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1256:63)
#16     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#17     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1232:20)
#18     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:543:41)
#19     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#23     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:46:7)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:641:31)
#2      LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:151:7)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#4      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:150:11)
#5      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:113:14)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#7      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:112:43)
#8      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1256:63)
#9      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#10     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1232:20)
#11     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:543:41)
#12     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#16     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1292:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1232:20)
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:543:41)
#4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#8      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

`analysis_options.yaml` in the root of the sdk:

```yaml
analyzer:
  exclude:
    - docs/newsletter/20171103/**
    - out/**
    - runtime/**
    - samples-dev/swarm/**
    - sdk/lib/**
    - sdk_nnbd/lib/**
    - tests/**
    - third_party/observatory_pub_packages/**
    - third_party/pkg/**
    - third_party/pkg_tested/dart_style/**
    - third_party/tcmalloc/**
    - tools/apps/update_homebrew/**
    - tools/dart2js/**
    - tools/dom/**
    - tools/sdks/dart-sdk/lib/**
    - tools/status_clean.dart
    - xcodebuild/**
```

@devoncarew: how do I find out on which file the analyzer crashes?

**Comment by devoncarew** [comment]
One of the crashes already mentions the file (pkg/front_end/testcases/general/having_part_with_parts_and_annotation_lib1.dart). It does look like there are two separate crashes here.

cc @scheglov

**Comment by bwilkerson** [comment]
@dcharkes There is anecdotal evidence that the piece of code that crashes analyzer might be in the front_end/testcases. You might be able to work around the issue temporarily by excluding some or all of those files.

@jensjoha There appears to be a mismatch between the `AstBuilder`'s expectations for which listener methods will be called and the actual set of invocations from the parser. I can't easily tell which side of the listener API is wrong. Can you look into it? I'm happy to make changes to `AstBuilder` if (a) that's the appropriate fix and (b) you're not comfortable doing so.

**Comment by dcharkes** [comment]
> @dcharkes There is anecdotal evidence that the piece of code that crashes analyzer might be in the front_end/testcases. You might be able to work around the issue temporarily by excluding some or all of those files.

That works: 1182 errors and 202 hints found.

(Side note: maybe can we add a builder that runs the analyzer on the whole sdk?)

Excluding this folder does not fix the mismatch in the `AstBuilder`.

**Comment by jensjoha** [comment]
It crashes on the file `pkg/front_end/testcases/extensions/extension_constructor.dart`.

Reproduction: `out/ReleaseX64/dart pkg/analysis_server/bin/server.dart --train-using pkg/front_end/testcases/extensions/` --- and yes it apparently has to go through the analysis_server. Running the cli (e.g. `touch analysis_options_empty.yaml && out/ReleaseX64/dart pkg/analyzer_cli/bin/analyzer.dart --packages=.packages --format=machine --dart-sdk=sdk/ --options=analysis_options_empty.yaml pkg/front_end/testcases/extensions/ && rm analysis_options_empty.yaml`) doesn't crash...

With that in mind I don't think this is a parser issue.

**Comment by jensjoha** [comment]
Update: Turns out it's not strictly true that analyzer_cli doesn't crash --- it does, it just swallows the exception... It *does* set an exit-code though (`3` in this case).

**Comment by jensjoha** [comment]
I think the analyzer needs the equivalent of 6ff8d2199da265e0aa2e3ca0b677956db3d42231, namely https://github.com/dart-lang/sdk/blob/ff1a3f7e3ad6b7e30eee6680c9d1353c791ce4e6/pkg/analyzer/lib/src/fasta/ast_builder.dart#L1743-L1750 doesn't throw anything away, explaining why on this input:

```
extension Extension on String {
  extension() {}
}
```

the stack in endExtensionDeclaration looks like this: `[extension, String]`, whereas on this:

```
extension Extension on String {
  Extension() {}
}
```

the stack looks like this: `[extension, String, NullValue.Metadata, Instance of '_Modifiers', NullValue.Type, Extension, NullValue.TypeVariables, (), NullValue.ConstructorInitializerSeparator, NullValue.ConstructorInitializers, {}]`.

This seems to fix the particular crash:
```
diff --git a/pkg/analyzer/lib/src/fasta/ast_builder.dart b/pkg/analyzer/lib/src/fasta/ast_builder.dart
index 2938cb22026..3d7a490c397 100644
--- a/pkg/analyzer/lib/src/fasta/ast_builder.dart
+++ b/pkg/analyzer/lib/src/fasta/ast_builder.dart
@@ -1747,6 +1747,16 @@ class AstBuilder extends StackListener {
     // extensions. They are invalid and the parser has already reported an
     // error at this point. In the future, we should include them in order
     // to get navigation, search, etc.
+
+    pop(); // body
+    pop(); // initializers
+    pop(); // separator
+    pop(); // parameters
+    pop(); // typeParameters
+    pop(); // name
+    pop(); // returnType
+    pop(); // modifiers
+    pop(); // metadata
   }
 
   @override
```

**Comment by bwilkerson** [comment]
@jensjoha Thanks for tracking this down! I've committed your fix in https://dart-review.googlesource.com/c/sdk/+/119680.

**Comment by dcharkes** [comment]
I can confirm that the crash in the IDE is gone. Thanks @bwilkerson and @jensjoha!

@bwilkerson The second crash (on the command line) still happens if I do not exclude `front_end/testcases`.

**Comment by bwilkerson** [comment]
@scheglov I think you're more familiar with that part of the code. Would you be able to take a look?

**Comment by stereotype441** [comment]
@dcharkes I tried the command-line repro from https://github.com/dart-lang/sdk/issues/38674#issuecomment-537456836, and it does still exit with exit code 3, however I don't believe that means that the analyzer is crashing and swallowing the exception.  The normal behavior of the analyzer CLI is to set its exit code based on the severity of errors it found; it finds errors in the code being analyzed (because the front_end testcases include code with deliberate errors), and so it sets an error code of 3 to indicate that.

So I believe this issue is fixed.  If I'm mistaken, please feel free to re-open.
