### ISSUE TITLE
[vm] Windows: throwing a string with unicode terminates abruptly

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/sdk#39687]
On Windows, in the command prompt, throwing a string with a unicode (non-ansi?) character terminates the program abruptly.

For instance running
```Dart
main() => throw "a→b";
```
prints
```
Unhandled exception:
a
```
whereas using `print` instead of throwing:
```Dart
main() => print("a→b");
```
correctly prints
```
a→b
```

@mkustermann

**Comment by ZichangG** [comment]
I can't reproduce anymore. This has been fixed?
This is what I get.
```
Unhandled exception:
a→b
#0      main (file:///C:/Users/zichangguo/dart-sdk/sdk/Junk/main.dart:1:11)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by johnniwinther** [comment]
I still have the problem on bleeding edge. It happens both in command prompt and PowerShell. I've tried running with various codepages (437, 850, 65001) but the problem persists.

I'm on Windows 10 Enterprise version 1709 OS Build 16299.1508 and running the X64 VM version.

**Comment by ZichangG** [comment]
I tried again with my windows machine with both debug and release build, but I'm not able to reproduce.

```
Dart VM version: 2.8.0-edge.21535e540f9ab7bfff73dd2a77b78abae360df93 (Tue Feb 4 22:37:35 2020 +0000) on "windows_x64"
```
I copied `main() => throw "a→b";` and run.

```
Unhandled exception:
a→b
#0      main (file:///C:/Users/zichangguo/dart-sdk/sdk/Junk/main.dart:1:11)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

I'm on Win 10 version 1903, OS Build 18362.592

@aam Could you try your windows machine to reproduce?

**Comment by aam** [comment]
Can't seem to reproduce the crash:

``` powershell
PS C:\src\dart-sdk\sdk> type .\throw.dart
main() => throw "aâ†’b";
PS C:\src\dart-sdk\sdk> .\out\DebugX64\dart .\throw.dart
Unhandled exception:
a→b
#0      main (file:///C:/src/dart-sdk/sdk/throw.dart:1:11)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

``` cmd
C:\src\dart-sdk\sdk>type throw.dart
main() => throw "a→b";
C:\src\dart-sdk\sdk>.\out\ReleaseX64\dart .\throw.dart
Unhandled exception:
a→b
#0      main (file:///C:/src/dart-sdk/sdk/throw.dart:1:11)
#1      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by ZichangG** [comment]
I'll close the issue since it cannot reproduce.

**Comment by johnniwinther** [comment]
I still have the same behavior on a freshly built VM on bleeding edge. Don't know what apparently makes my setup different.
