### ISSUE TITLE
Float32x4, Int32x4 with.. methods do not check for null arguments

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#40240]
CL https://dart-review.googlesource.com/c/sdk/+/132341 ports 'lib_2/typed_data/simd_type_null_params_weak_test.dart' to nnbd, and the resulting 'lib/typed_data/simd_type_null_params_weak_test.dart' shows that the configuration dartdevk-weak-linux-release-chrome fails to check the parameters of the following instance methods:

```dart
void main() {
  dynamic dynamicNull = null;
  final float32x4 = Float32x4(0.0, 0.0, 0.0, 0.0);

  float32x4.withX(dynamicNull);
  float32x4.withY(dynamicNull);
  float32x4.withZ(dynamicNull);
  float32x4.withW(dynamicNull);

  final int32x4 = Int32x4(0, 0, 0, 0);

  int32x4.withX(dynamicNull);
  int32x4.withY(dynamicNull);
  int32x4.withZ(dynamicNull);
  int32x4.withW(dynamicNull);
}
```

The methods are declared to accept an argument of type `double`, so the argument should be subject to a dynamic type check at run time, and it should fail. However, the invocations complete normally.

Other methods of `Float32x4` (e.g., `min` and `max`) do have this check, it's specifically the `with..` methods that fail to have it.

**Comment by sigmundch** [comment]
This should be addressed by Vijay's change https://github.com/dart-lang/sdk/commit/b706395788b2d079244aebb9786e24f4543b6470

**Comment by nshahan** [comment]
We closed this issue but with that change that Vijay landed we only throw in strong mode. Weak mode issues a warning. The weak mode test that @eernstg mentioned is still failing. Do we really want to expect failures when passing null in weak mode? Did we include this as a breaking change?

**Comment by eernstg** [comment]
I think we should reopen this issue. Here's why:

First note that the commit https://github.com/dart-lang/sdk/commit/b706395788b2d079244aebb9786e24f4543b6470 should not be relevant to this issue, because (by the title, and as far as I can see on a quick scan) it is concerned with strongly checked execution. The test failure reported in this issue occurs during weakly checked execution.

This issue is actually about the implementation of the methods `with...` in the classes `Float32x4` and `Int32x4`, and it arose because different configurations behave differently.

It is not difficult to see why. With the vm we have the [following](https://github.com/dart-lang/sdk/blob/9a588de9f4dad07e9ffce1012eef1c1470817da3/sdk_nnbd/lib/_internal/vm/lib/typed_data_patch.dart#L3574):

```dart
class _Float32x4 implements Float32x4 {
  ...
  Float32x4 withX(double x) {
    _throwIfNull(x, 'x');
    return _withX(x);
  }
  ...
}
```

which will perform the dynamic check for null in the body of the method (and similarly for `withY` etc.). In contrast, we have [this](https://github.com/dart-lang/sdk/blob/9a588de9f4dad07e9ffce1012eef1c1470817da3/sdk_nnbd/lib/_internal/js_runtime/lib/native_typed_data.dart#L1353) in 'js_runtime/lib/native_typed_data.dart':

```dart
class NativeFloat32x4 implements Float32x4 {
  ...
  Float32x4 withX(double newX) {
    return NativeFloat32x4._truncated(_truncate(newX), y, z, w);
  }
  ...
}
```

and identical code in 'js_dev_runtime/private/native_typed_data.dart'.

Of course, there won't be a dynamic type error based on the language semantics when we pass null to a method accepting `double` in weak checking mode. So it's no surprise that we don't get an exception when `withX` is called with the argument null (of static type `dynamic`). It could fail later on (maybe `_truncate` will throw when called on null), but apparently it just allows null everywhere we go, in the given test.

However, in order to ensure that we preserve the _existing_ (pre-null-safety) level of invariant enforcement when system library methods are invoked during a weakly checking program execution, we have preserved the argument type checks in system library methods. So there are lots of situations where an argument whose value "couldn't be null" (according to the sound-null-safety rules) is still null-checked, so that weak checking execution isn't _worse_ than pre-null-safety behavior.

So the only problem is that these manual null checks are missing from the `with...` methods in `Float32x4 and `Int32x4` on some platforms.

The question is whether it is a breaking change to introduce these null checks, and whether it's serious enough to call for a breaking change process.

Note that the null checks are already present on some platforms, and on other methods than `with...`, and that the implicit `null as double` check which will be performed when the same test is executed in with strong checking. So anyone who is passing null as in this test would not get away with it on other platforms now, or on any platform when switching to `--sound-null-safety`.

**Comment by nshahan** [comment]
@rakudrama DDC and Dart2js have similar failures on this test. Let's find some agreement in how we resolve it.

**Comment by sigmundch** [comment]
My inclination is to leave things as they are at this time.

It seems this is not anymore about implementing the null semantics, but about fixing an existing VM/web inconsistency bug (and as a result it would be a bug breaking change). My inclination is to treat this like any other API that we tighten in the SDK: we made the type non-nullable, but we don't introduce a breaking change now. We let the migration to null safety be the driver for moving towards that non nullable API instead.

**Comment by rakudrama** [comment]
We could leave things as they are for the reasons Siggi mentions.
But this is a relatively simple way to +1 our passing tests.

I would want to fix the problem for two reasons
- The failing test case makes us blind to regressions on all the other tests in the file.
- `Float32x4.withX(dynamicNull)` might assign _0.0_ or _NaN_ depending of the null value.
- I don't think this rises to the requirements of the breaking change process. These APIs are very lightly used on the web, and most likely in code ported from native, where there is a performance advantage to using the API.

**Comment by modulovalue** [comment]
Is this still an issue in 2026 long after nnbd?

**Comment by rakudrama** [comment]
Thanks for asking, this is no longer relevant.

We can also remove the `checkNum` calls from the methods.

**Comment by nshahan** [comment]
@rakudrama 
I don't remember all the context here. We have a lot of argument checking in this library that looks pointless given the static types of the parameters. Beyond `checkNum` there are checks like: 

https://github.com/dart-lang/sdk/blob/d87cf30c54787de5c4b1ebf763ae189c013c156d/sdk/lib/_internal/js_runtime/lib/native_typed_data.dart#L1537-L1548
or 

https://github.com/dart-lang/sdk/blob/d87cf30c54787de5c4b1ebf763ae189c013c156d/sdk/lib/_internal/js_runtime/lib/native_typed_data.dart#L1896-L1905

Are there JavaScript values flowing to these constructors that would make these checks necessary still?

**Comment by rakudrama** [comment]
Tests like the quoted snippets can be removed.
