### ISSUE TITLE
Bots are red because of superseded unapproved failures

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#40418]
Currently there are 2 red bots, [vm-kernel-precomp-obfuscate-linux-release-x64](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-precomp-android-release-arm_x64/972) and [vm-kernel-precomp-android-release-arm_x64](https://ci.chromium.org/p/dart/builders/ci.sandbox/vm-kernel-precomp-obfuscate-linux-release-x64/6054) due to red test results step.

Stdout for this step says

```
 No unapproved new failures
 There are unapproved failures from previous builds
 Failures link: https://dart-ci.firebaseapp.com/#showLatestFailures=true&showUnapprovedOnly=true&configurationGroups=vm
```

Link https://dart-ci.firebaseapp.com/#showLatestFailures=true&showUnapprovedOnly=true&configurationGroups=vm doesn't show anything.

On test results feed there are following unapproved failures:
```
[vm] Add support for real unboxed floating point fields in AOT
9eb531 victor.agnez@hotmail.com 5:45 Thu Jan 30

dartkp-android-release-arm_x64
RuntimeError -> Crash (expected Pass)
language_2/async_star/cancel_while_paused_at_yield_test
service/bad_reload_test
service/break_on_activation_test
service/break_on_default_constructor_test
service/breakpoint_in_package_parts_class_file_uri_test
service/breakpoint_in_parts_class_test
service/breakpoint_on_if_null_3_test
service/complex_reload_test
service/debugging_test
service/dev_fs_spawn_test
service/eval_internal_class_test
service/evaluate_activation_test/none
service/evaluate_activation_test/scope
service/evaluate_async_closure_test
service/evaluate_with_escaping_closure_test
service/issue_30555_test
service/next_through_assign_call_test
service/next_through_await_for_test
service/next_through_call_on_field_in_class_test
service/next_through_call_on_field_test
service/next_through_call_on_static_field_in_class_test
service/next_through_catch_test
service/next_through_create_list_and_map_test
service/next_through_for_loop_with_break_and_continue_test
service/next_through_function_expression_test
service/next_through_multi_catch_test
service/next_through_new_test
service/next_through_simple_async_test/0
service/next_through_simple_async_test/1
service/next_through_simple_async_with_returns_test/0
service/next_through_simple_async_with_returns_test/1
service/next_through_simple_linear_2_test
service/pause_on_exceptions_test
service/pause_on_start_then_step_test
service/pause_on_unhandled_async_exceptions2_test/1
service/pause_on_unhandled_async_exceptions_test/1
service/pause_on_unhandled_exceptions_test
service/regress_28443_test
service/step_through_arithmetic_test
service/step_through_constructor_calls_test
service/step_through_constructor_test
service/step_through_for_each_sync_star_2_test
service/step_through_for_each_sync_star_test
service/step_through_function_2_test
service/step_through_function_test

dartkp-obfuscate-linux-release-x64
new test -> RuntimeError (expected Pass)
service/dominator_tree_vm_with_double_field_test/0
service/dominator_tree_vm_with_double_field_test/1
service/dominator_tree_vm_with_double_field_test/2
```

That change was already reverted and failures on revert were approved.

Also, if I look at their results.json, I can see that unapproved tests are failing with `RuntimeError` or not present (for dartkp-obfuscate-linux-release-x64). So their status returned back to the state before that change.

/cc @athomas @whesse

**Comment by athomas** [comment]
This is not a P0, the redness on CI shouldn't affect the CQ. It's just reverted failures that keep the builders on CI red. This is a UI bug.

**Comment by alexmarkov** [comment]
@athomas Thank you for taking a look and setting correct priority. Can you suggest a workaround? How can we make sure that there are no new failures while those bots are red?

**Comment by athomas** [comment]
The results feed will show all new failures as usual. Monitor the
unapproved failures there. The failures that currently keep the bot red
could also be approved and they will no longer show (that should have
happened automatically when they were superceded by newer results but
because of a bug it didn't.

**Comment by alexmarkov** [comment]
As a workaround, the failures corresponding to https://github.com/dart-lang/sdk/commit/9eb531bde45ae7b8417ff86cbb5f9ea496de50ae were approved.

**Comment by alexmarkov** [comment]
For the same reason vm-kernel-precomp-linux-debug-x64  and vm-kernel-precomp-linux-debug-simarm_x64 are currently still red:
- A lot of tests start crashing after bada62ba7bd6d71f446fe9b58a54803aa03ba815. Some of them changed from RuntimeError to Crash.
- The fix 7a6233ad51d0d24973a1f205a53b9421dcb90315 landed, changing status of those tests back to RuntimeError.
- Bot remains red, and there are still unapproved failures in the results feed (although those tests returned back to the state they were before the first change).

**Comment by athomas** [comment]
We've landed various fixes since then. I believe this has been resolved.

**Comment by whesse** [comment]
I wouldn't say this is totally fixed, but we can make a new issue tracking the various ways this may still happen.
I have a CL out that fixes the case where a failure is marked as flaky before it is approved or fixed, but in the (rare) case that a chunk of results fails to be processed, and a fix for a failure is missed, it will become red.  Longer term fixes to avoid chunks and cloud functions that can fail on a chunk will be the fix for that.
