### ISSUE TITLE
Constant evaluation results in non-nullable types in unforked SDK

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#40526]
Without strong mode (in weak mode or when NNBD experiment is not enabled)  constants should use legacy types.

https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#const-evaluation-and-canonicalization

To reproduce the problem, build NNBD SDK (or patch in https://dart-review.googlesource.com/c/sdk/+/134808), then run the following example without enabling NNBD experiment.

```dart
main() {
  var c1 = const [3 ~/ 3];
  var c2 = const [1];
  print(identical(c1, c2));
}
```

Kernel file without NNBD experiment enabled:
```
  static method main() → dynamic {
    core::List<core::int>* c1 = #C2;
    core::List<core::int*>* c2 = #C3;
    core::print(core::identical(c1, c2));
  }

  #C1 = 1
  #C2 = <core::int>[#C1]
  #C3 = <core::int*>[#C1]
 ```

With NNBD experiment enabled but library is opted-out constant uses legacy type, but inferred type argument is still non-nullable:
```
  static method main() → dynamic {
    core::List<core::int>* c1 = #C2;
    core::List<core::int*>* c2 = #C2;
    core::print(core::identical(c1, c2));
  }

  #C1 = 1
  #C2 = <core::int*>[#C1]
```

/cc @johnniwinther

**Comment by vsmenon** [comment]
Is this an unfork blocker?  Do we still have a canonicalization issues?

**Comment by johnniwinther** [comment]
This seems to have been fixed. @alexmarkov can you verify?

**Comment by alexmarkov** [comment]
@johnniwinther I can still reproduce this bug on ToT.

@vsmenon I think it blocks unforking because it is an observable and incorrect change in behavior.
`co19_2/Language/Expressions/Lists/identical_t01` test fails with unforked SDK due to this bug.

Repro:
```
tools/test.py -n dartk-linux-release-x64 co19_2/Language/Expressions/Lists/identical_t01
```
