### ISSUE TITLE
dart executed via symlink fails on mac

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#41329]
Dart VM version: 2.8.0-dev.20.0 – SHA 803c0cd8da8125af1fe3a73970d66af892775fb7

brew installs dart in

`$BREW/Cellar/dart/2.8.0-dev.20.0/libexec/bin`

symlink is added to
`$BREW/bin/dart` -> `../Cellar/dart/2.8.0-dev.20.0/bin/dart`

`$BREW/bin` is on path

```console
> dart bin/some_exe.dart
Error: Error when reading 'bin/some_exe.dart': No such file or directory
```

```console
> $BREW/bin/dart bin/some_exe.dart
Error: Error when reading 'bin/some_exe.dart': No such file or directory
```

This works fine
```console
> $BREW/Cellar/dart/2.8.0-dev.20.0/libexec/bin/dart bin/some_exe.dart
All good!
```

Something with how the dart exe determines it's working directory seems very broken – at least on mac!

**Comment by kevmoo** [comment]
https://github.com/dart-lang/sdk/commit/99a5117411f9b9fae2866dee85573e9894db1f46 seems like it could be a culprit – CC @bkonyi

**Comment by bkonyi** [comment]
Should be fixed in https://dart-review.googlesource.com/c/sdk/+/142440

**Comment by a-siva** [comment]
Instead of moving forward with another change I am wondering if it be more safe to do a cherry pick that reverts this change in 2.8, the change was made for dartdev which is not a feature for 2.8

**Comment by a-siva** [comment]
Since we have a revert for this to be merged into the dev release bumping down priority from P0 to P2

**Comment by franklinyow** [comment]
Change to P1 to reflect priority for cherrypick, P2 will not meet the bar
Added merge-to-beta, merge-to-dev label for cherrypick process

**Comment by athomas** [comment]
Temporary workaround for homebrew until this goes out in the dev channel is to install the beta upcoming channel:
```sh
$ brew unlink dart
$ brew install dart-beta
$ dart --version
Dart VM version: 2.8.0-dev.20.7 (beta) (Tue Apr 14 08:59:52 2020 +0200) on "macos_x64"
```

**Comment by kevmoo** [comment]
It's a bit weird that there are fixes in beta not in dev... 🤷

**Comment by athomas** [comment]
@kevmoo I'm working on dev as well. We're in a bit of a weird state because of alignment with Flutter versioning.

**Comment by a-siva** [comment]
Do we need some tweaking in the cherry pick process to ensure the merges flow first into dev and then into beta?

**Comment by athomas** [comment]
No, this is purely temporary and a technical rather than a process issue.

**Comment by kevmoo** [comment]
@bkonyi – this is back in the latest dev release - 2.9.0-1.0.dev

**Comment by kevmoo** [comment]
Verified fixed in `2.9.0-3.0.dev (dev)` – thanks @bkonyi !

**Comment by bkonyi** [comment]
Thank you for verifying @kevmoo! May this issue remain closed for the rest of time...

**Comment by devoncarew** [comment]
I'm still see brew issues w/ the latest dev; is that expected? There's nothing left to merge?

```
dart analyze  
Could not find DartDev snapshot and 'analyze' is not a valid script.

dart --version
Dart VM version: 2.9.0-7.0.dev (dev) (Thu May 7 09:17:54 2020 +0200) on "macos_x64"
```

**Comment by bkonyi** [comment]
Hm, not sure what the issue was, but it seems to disappear when I replace the last symlink in the brew install to point towards my locally built SDK. I've been fiddling with the options parsing quite a bit over the last week, so it could be that this was just a temporary failure that's been fixed in a follow up CL that came after we created the dev build.

Let's confirm whether or not this issue is still occurring once we create the next dev release.

**Comment by bkonyi** [comment]
Confirmed that we're seeing this again.

**Comment by bkonyi** [comment]
@devoncarew can you confirm this is resolved in 2.9.0-13.0.dev? It seems like it's working on my end now.

**Comment by devoncarew** [comment]
Yup! It started working as of the last time I checked, ~last week. Thanks!

**Comment by bkonyi** [comment]
Awesome! Thanks for confirming!
