### ISSUE TITLE
set breakpoint on core library

### ISSUE THREAD

**Issue by linyu92** [dart-lang/sdk#41423]
How can I make a breakpoint work on dart:core?

**Comment by vsmenon** [comment]
What debugging tool are you using?  An IDE?  Dart DevTools?  Are you debugging a native app?  Command line?  Flutter?  Web?

Note, VSCode at least has a preference to indicate whether you want to debug the SDK or not.  It may default to off.

For questions, you may get better and faster responses on a different channel: https://dart.dev/community#join-the-conversation

**Comment by linyu92** [comment]
@vsmenon thanks for your reply.

I am using VSCode debugging a dart program and turn  "dart.debugSdkLibraries" on as well. Then I code as below:

```
import 'dart:io';

void main() async {
    final client = HttpClient(); // set breakpoint here
    final request = await client.getUrl(Uri.parse("https://www.google.com/")); 
    final response = await request.close();
}
```

When I step into the `HttpClient()` , VSCode can't break at the right position. I'm a dart beginner and learning about the core library now. I will appreciate that If it can step into the sdk library!

**Comment by vsmenon** [comment]
Are you debugging a native app? Command line? Flutter? Web?

**Comment by linyu92** [comment]
Just a hello.dart without any dependency.

**Comment by linyu92** [comment]
I am curious how the SDK library  is developed, like `dart:io`, ``dart:async` or any other else, if the SDK cannot be debugged by the developer.

**Comment by vsmenon** [comment]
@DanTup - do you know if VSCode is paying attention to that flag?  It wasn't working for me on the web recently either (but I could in Chrome DevTools).  

This appears to be a command line app.

**Comment by vsmenon** [comment]
I.e., "dart.debugSdkLibraries"

**Comment by DanTup** [comment]
I tested with the code above, and seem to be able to reproduce this - stepping into HttpClient goes further than you'd expect:

<img width="689" alt="Screenshot 2020-04-14 at 21 43 33" src="https://user-images.githubusercontent.com/1078012/79272373-428f3900-7e99-11ea-86fc-91e36373f77c.png">

<img width="872" alt="Screenshot 2020-04-14 at 21 44 17" src="https://user-images.githubusercontent.com/1078012/79272388-46bb5680-7e99-11ea-8bfd-7a7ab1627f99.png">

The HttpClient frame is greyed in the call stack, suggesting we didn't consider it debuggable. I checked the source, and came across this issue:

https://github.com/dart-lang/sdk/issues/29813

It seems like trying to set internal libraries (`dart:_`) to debuggable might not work, which might be why this is happening. I'm not really sure what the expected behaviour is there, as there hasn't been a response on that issue. Do you know who might know about this?

> do you know if VSCode is paying attention to that flag? It wasn't working for me on the web

Things are a bit different on web - setLibraryDebuggable isn't implemented so we can't control which libraries are debuggable from VS Code (see https://github.com/dart-lang/webdev/issues/606).

**Comment by mraleph** [comment]
Duplicate of #29813

**Comment by DanTup** [comment]
Being able to step into dart:_ libraries is fixed in v2.9.0 of the SDK but also needs a VS Code change before it'll work there (done in https://github.com/Dart-Code/Dart-Code/issues/2423 - which will ship in the next release).

**Comment by hahai96** [comment]
@DanTup , I'm using flutter 2.2.1 and dart 2.13.1, but still can't debug in dart core
<img width="1259" alt="Screen Shot 2021-08-21 at 5 05 07 PM" src="https://user-images.githubusercontent.com/23280338/130318357-8691dab7-52ee-47ca-a35c-e38c049b0187.png">

**Comment by DanTup** [comment]
@hahai96 please file a new issue at https://github.com/flutter/flutter-intellij/ if you're using Android Studio/IntelliJ with a clear description/repro for the issue. Thanks!
