### ISSUE TITLE
VM service no longer tolerates missing `"jsonrpc"="2.0"` or missing `params` fields

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#41942]
Recent VM versions now through if you miss the `jsonrpc="2.0"` attribute on requests to the VM service:

```
==> {"id":"0","method":"getVersion"}
<== {"jsonrpc":"2.0","error":{"code":-32600,"message":"Request must contain a \"jsonrpc\" key.","data":{"request":{"id":"0","method":"getVersion"}}},"id":"0"}
```

This is probably correct behaviour, however it was also a somewhat breaking change (it broke VS Code - see https://github.com/Dart-Code/Dart-Code/issues/2464, though I've pushed to resolve it as long as people upgrade).

Additionally, missing `params` fields are now rejected (I'm less sure about the validity of this though, as jsonrpc suggests `params` may be omitted:

```
==> {"jsonrpc":"2.0","id":"0","method":"getVersion"}
<== {"jsonrpc":"2.0","error":{"code":-32602,"message":"Parameters for method \"getVersion\" must be passed by name.","data":{"request":{"jsonrpc":"2.0","id":"0","method":"getVersion"}}},"id":"0"}
```

@bkonyi FYI!

**Comment by bkonyi** [comment]
As explained in https://github.com/Dart-Code/Dart-Code/issues/2464#issuecomment-630329307, this is caused by request verification in package:json_rpc_2 which is being used by DDS. Since it would likely be a significant amount of work to allow for clients to omit the jsonrpc and param keys compared to updating the clients to send properly formatted requests, this likely won't be fixed.

**Comment by DanTup** [comment]
@bkonyi Understood - though if I'm understanding correctly, the jsonrpc spec says that `params` may be omitted - so this one seems like maybe a bug?

> `params`
> A Structured value that holds the parameter values to be used during the invocation of the method. **This member MAY be omitted.**

**Comment by bkonyi** [comment]
I haven't gone digging through the spec myself, but that's a fair point. @kevmoo might have an opinion on this, but it would be a quick fix.

**Comment by DanTup** [comment]
I think the `getVersion` change is a result of adding `isolateIds`:

https://github.com/dart-lang/sdk/commit/93c9ebabd6f5b63b0bb64a26f9bb06dc6964a486#diff-b1ec2d66991192adf3d1413308a02939

This results in calls to here, which throws if there was no `params` object at all:

https://github.com/dart-lang/json_rpc_2/blob/2e6c9a70e22bd78e2d002393038e481ec95a89ed/lib/src/parameters.dart#L47

**Comment by DanTup** [comment]
Btw - the Dart VM service spec explicitly says:

> The Service Protocol optionally accepts requests without the jsonprc property.

If that won't be the case, it should probably be stripped and a note added to its changelog.

**Comment by bkonyi** [comment]
> I think the `params` change is a result of adding `isolateIds`:
> 
> [93c9eba#diff-b1ec2d66991192adf3d1413308a02939](https://github.com/dart-lang/sdk/commit/93c9ebabd6f5b63b0bb64a26f9bb06dc6964a486#diff-b1ec2d66991192adf3d1413308a02939)
> 
> This results in calls to here, which [throws](https://github.com/dart-lang/json_rpc_2/blob/2e6c9a70e22bd78e2d002393038e481ec95a89ed/lib/src/parameters.dart#L56) if there was no `params` object at all:
> 
> https://github.com/dart-lang/json_rpc_2/blob/2e6c9a70e22bd78e2d002393038e481ec95a89ed/lib/src/parameters.dart#L47

I don't think so, since that CL just updates incorrect documentation for the dart:io service protocol extensions and didn't change the actual implementation.



> Btw - the Dart VM service spec explicitly says:
> 
> > The Service Protocol optionally accepts requests without the jsonprc property.
> 
> If that won't be the case, it should probably be stripped and a note added to its changelog.

Ah, I didn't realize that was there. Thanks for pointing that out!

**Comment by DanTup** [comment]
> I don't think so, since that CL just updates incorrect documentation for the dart:io service protocol extensions and didn't change the actual implementation.

Oh right, I didn't read far enough 😄 I'm not sure when this broke then - did some of the implementation change over to json_rpc_2 recently and maybe the previous version was less strict? I wasn't sure where the implementation lived for this (I saw some C code, but since that error seems to come from the json_rpc_2 Dart package, I'm not sure that's it).

**Comment by bkonyi** [comment]
99.99% sure it was [this CL](https://dart-review.googlesource.com/c/sdk/+/147980) that would have caused the breakages. We never used package:json_rpc_2 in the standalone VM service (we don't depend on external packages in `dart:_vmservice`), but since the Dart Development Service (DDS) didn't have any restrictions on package use I used shelf and json_rpc_2 to keep things as simple as possible. In the CL above, I updated the VM to always run with DDS enabled when the VM service is enabled. This was meant to be a transparent change as DDS is a VM service intermediary that advertises itself as the real service, but apparently my attempt at being sneaky didn't work out as planed :(

**Comment by a-siva** [comment]
Should this issue be reopened based on the comment above ?

**Comment by DanTup** [comment]
@a-siva based on discussions that continued in the original thread (https://github.com/Dart-Code/Dart-Code/issues/2464#issuecomment-630370355) I think so - @bkonyi is making a PR for `json_rpc_2` to support a less-strict mode. (I don't have the power to re-open it).

**Comment by MichaelRFairhurst** [comment]
I stumbled across this because I'm hitting this in my code coverage guided fuzzing package.

Reopening -- seems like there is work to do here and I have the power. If there's a better action than reopening, may the reopening prompt that action :)

**Comment by MichaelRFairhurst** [comment]
FWIW, I was able to work around this by upgrading package vm_service.

**Comment by DanTup** [comment]
It looks like this should be fixed by the changeset above (01fd2c480e7c1e3f4c3ad37a96900eb1be659060). However, using the nightly build made just this morning, I'm still seeing this:

```
Dart SDK:
    Loc: /Users/danny/Dev/Dart SDKs/nightly-2020-05-20
    Ver: 2.9.0-edge.17ff769f0a0dd8adeeb821d5e0fadeefd1e38424


 Spawning /Users/danny/Dev/Dart SDKs/nightly-2020-05-20/bin/dart remotely with args ["--enable-vm-service=0","--pause_isolates_on_start=true","--write-service-info=file:///var/folders/b1/ftm2whhj4mb3_c4nfjhq23z00000gn/T/dart-vm-service-2542.json","-DSILENT_OBSERVATORY=true","--enable-asserts","bin/main.dart"]
 ==> {"id":"0","method":"getVersion"}
 <== {"jsonrpc":"2.0","error":{"code":-32600,"message":"Request must contain a \"jsonrpc\" key.","data":{"request":{"id":"0","method":"getVersion"}}},"id":"0"}
```

@bkonyi any idea why this might still be failing? The git hash in the version above points to a much more recent commit than the fix.

**Comment by bkonyi** [comment]
Looks like I missed a spot where we use `json_rpc.Peer`. Should be fixed by [this CL](https://dart-review.googlesource.com/c/sdk/+/148781).

**Comment by DanTup** [comment]
@bkonyi still seeing the `params` issue with the latest nightly (last line of log):

```
Dart SDK:
    Loc: /Users/danny/Dev/Dart SDKs/nightly-2020-05-27
    Ver: 2.9.0-edge.b95a1bd567457baf05a4b969c00b076b72805409

Spawning /Users/danny/Dev/Dart SDKs/nightly-2020-05-27/bin/dart remotely with args ["--enable-vm-service=0","--pause_isolates_on_start=true","--write-service-info=file:///var/folders/b1/ftm2whhj4mb3_c4nfjhq23z00000gn/T/dart-vm-service-3392.json","-DSILENT_OBSERVATORY=true","--enable-asserts","bin/main.dart"]
..  in /Users/danny/Desktop/dart_sample
    PID: 25410
Starting to poll for file /var/folders/b1/ftm2whhj4mb3_c4nfjhq23z00000gn/T/dart-vm-service-3392.json
Succesfully read JSON from /var/folders/b1/ftm2whhj4mb3_c4nfjhq23z00000gn/T/dart-vm-service-3392.json
Stopping polling for file /var/folders/b1/ftm2whhj4mb3_c4nfjhq23z00000gn/T/dart-vm-service-3392.json
Initialising debugger for ws://127.0.0.1:59004/0Zfu4evvqdg=/ws
Connecting to VM Service at ws://127.0.0.1:59004/0Zfu4evvqdg=/ws
==> {"id":"0","method":"getVersion"}
<== {"jsonrpc":"2.0","error":{"code":-32602,"message":"Parameters for method \"getVersion\" must be passed by name.","data":{"request":{"id":"0","method":"getVersion"}}},"id":"0"}
```

**Comment by bkonyi** [comment]
@DanTup I'm guessing this is a local build of the SDK? If so, have you run `gclient sync` recently?

**Comment by DanTup** [comment]
@bkonyi this was using a nightly build from http://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/, so it should have all the correct versions of everything.

**Comment by DanTup** [comment]
@bkonyi did you get chance to check this? The latest version of the VS Code extension sends `{}` in place of empty params, but if there are other tools not doing so they may break as this change propagates.

**Comment by bkonyi** [comment]
Not yet. I'll take a look today.

**Comment by bkonyi** [comment]
@DanTup it should be fixed now. Just took a 5 character change :-)

**Comment by DanTup** [comment]
@bkonyi yep, fix looks good now - thanks! It may be worth a test to ensure this doesn't regress (since not passing `params` is by-spec as I understand it).

For VS Code, I'll leave the `{}` in for now, to avoid confusion if a build without that fix ended up in anyones Flutter channels.
