### ISSUE TITLE
Analyzer doesn't handle mixin inference across opted in/opted out boundaries

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#42605]
The following example relies on mixin type argument inference in the definition of `_StepperState`.   If both files are opted in, or both opted out, then mixin inference works correctly.  However, if the first file is opted in and the second opted out (as shown below) the analyzer fails to infer the type argument to `TickerProviderStateMixin`.

opted_in.dart
```dart
// @dart = 2.9

abstract class State<T> {}
mixin TickerProviderStateMixin<T> on State<T> {}
```

opted_out.dart
```dart
// @dart = 2.8
// Opted-out library.

import 'opted_in.dart';

class Stepper { }
class _StepperState extends State<Stepper> with TickerProviderStateMixin { }
```

cc @a14n @scheglov

**Comment by devoncarew** [comment]
@scheglov - can you take a look at this?

**Comment by scheglov** [comment]
@leafpetersen Is mixin type arguments inference specified somewhere?

I can reproduce the issue with the following test:
```dart
  solo_test_XXX() async {
    newFile('/test/lib/a.dart', content: r'''
// @dart = 2.8
abstract class A<T> {}
mixin M<T> on A<T> {}
''');
    await assertNoErrorsInCode(r'''
import 'a.dart';

class B extends A<int> with M {}
''');
  }
```

When we want to infer type arguments for `M` in `B`, we do subtype matching `A<T*>* <# A<int>` and `A<int> <# A<T*>*`. Solving these constraints gives us `T = int`. But then we do one more check:
```dart
    for (int i = 0; i < srcTypes.length; i++) {
      if (substitution.substituteType(srcTypes[i]) != destTypes[i]) {
        // Failed to find an appropriate substitution
        return null;
      }
    }
```

This check fails because when we apply `T = int` to `on A<T*>*` we get `A<int*>*`, but in the NullSafe library we require `A<int>`. It seems that equality is a wrong check here, what should we replace it with? Also, do we need it at all (this is why I'd like to see what the specification says about it)?

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/153482 should fix the issue for in-order migration, when the mixin is declared in NullSafe library, and the mixin application is in a legacy library.

The out-of-order case requires some spec work, if I understand it correctly.

**Comment by scheglov** [comment]
`flutter-analyze-try` bot is failing with my CL, and still continues to fail.
But it fails for my other CLs too.
So, I landed my CL, and hope that it does not break anything new.

**Comment by jakemac53** [comment]
There is a slightly more complicated case that I think is still broken here:

a.dart
```dart
// @dart=2.10
class A<T> {}

mixin B<T> on A<T> {}
mixin C<T> on A<T> {}
```
b.dart
```dart
// @dart=2.8
import 'a.dart';

class D extends A<int> with B<int>, C {}
```

cc @scheglov

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/161322
