### ISSUE TITLE
non-nullable not working with TickerProviderStateMixins (or AnimationControllers)

### ISSUE THREAD

**Issue by TriMontana** [dart-lang/sdk#43615]
I have refactored tons of code to use the non-nullable approach, using sdk 2.9 or later.  It appears to be 99.1% backwards compatible.   I'm able to get everything to work except classes that used the TickerProviderStateMixins (including Single version).  I continue to get this error:    

_error1: Type parameters couldn't be inferred for the mixin 'TickerProviderStateMixin' because no type parameter substitution could be found matching the mixin's supertype constraints (mixin_inference_no_possible_substitution at [MyApp]_  

_error2: _The class 'MyApp' cannot implement both 'State<MyApp>' and 'State<StatefulWidget*>*' because the type arguments are different._

I have tried it with any number of code sets, including numerous ones from  Flutter tutorials for AnimationController, such as [https://flutter.dev/docs/development/ui/animations/tutorial](url).  However, they all produce the same errors, regardless of IDE, OS, and complexity of code.  This is easily reproducible using any Flutter example with the Ticker mixins after switching to the non-nullable approach (I switched by updating the .yaml).

**Comment by leafpetersen** [comment]
@TriMontana what's the latest SDK you've tried this with (I know there were some bugs around mixin inference that have been fixed).  Also, are you seeing this in the IDE, using flutter analyze, flutter run, or all of the above?

**Comment by TriMontana** [comment]
Hello and thanks for your quick response.  I tried it briefly using the beta channel and 2.10.0 this a.m. but still no luck. I didn't have much time to devote to it due to other priorities, so I might be missing something simple in the settings. I've now switched back to SDK 2.9.3 on stable and have used clean builds and invalidated caches to start anew (but still the problem). So I'll have to rework that code to bypass AnimationContoller for now.  I have tried it with both VS Code and Android Studio, using the IDE plugins to pulldown the Dart and Flutter SDKs as well as pulling them down manually.  I'm seeing the errors in both of the IDEs, so the errors do not allow me to compile the code and run any debugging (or I'm not familiar with how to debug without compiled code).  Hope you can help or point me in the right direction that component is key to the app.  Thanks.

**Comment by leafpetersen** [comment]
@TriMontana do I understand correctly that your code works before you opt it in, and fails afterward?  You may be able to work around this by providing explicit type arguments to SingleTickerProviderStateMixin, e.g.

```
            class _LogoAppState extends State<LogoApp> with SingleTickerProviderStateMixin<LogoApp>
```

@scheglov Are there any known issues around this? We don't have a concrete reproduction yet unfortunately.

**Comment by TriMontana** [comment]
Great! That works perfectly, i.e.  providing explicit type arguments to SingleTickerProviderStateMixin.
Thanks so much!

            class _LogoAppState extends State<LogoApp> with SingleTickerProviderStateMixin<LogoApp>

**Comment by scheglov** [comment]
@leafpetersen I think https://github.com/dart-lang/sdk/issues/42605#issuecomment-655097555 - we might need spec / support for out-of-order case.

**Comment by devoncarew** [comment]
@scheglov - do we need a spec update to make progress here? And, is this something we'l want for nnbd stable?

**Comment by scheglov** [comment]
I'm not able to reproduce this issue. This code is resolved without errors in the analyzer.
```dart
abstract class LogoApp extends StatefulWidget {}
abstract class _LogoAppState extends State<LogoApp> with SingleTickerProviderStateMixin {}
```

**Comment by srawlins** [comment]
Closing as stale.
