### ISSUE TITLE
Infra failure on flutter-frontend-try

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43807]
I'm seeing infra failures with my [flag flip CL](https://dart-review.googlesource.com/c/sdk/+/166790) for null safety that I don't really know how to debug.  See [here](https://ci.chromium.org/p/dart/builders/try/flutter-frontend-try/370?) for log.

@athomas who's the right person to look into this?

**Comment by athomas** [comment]
Thanks, that's an infra issue. The script is in https://github.com/flutter/buildroot/blob/master/tools/dart/create_updated_flutter_deps.py (in Flutter's buildroot which isn't checked-out by the flutter-frontend builder).

**Comment by athomas** [comment]
https://dart-review.googlesource.com/c/sdk/+/167806 should fix it.

**Comment by leafpetersen** [comment]
I'm still seeing an [infra failure](https://ci.chromium.org/p/dart/builders/try/flutter-frontend-try/387?) with the fix above included, is it getting farther and failing somewhere else, or does this need to roll somewhere?

**Comment by athomas** [comment]
The test runner exits with exit code 1, this may be an issue with the CL so I've asked @jensjoha to take a look. I don't see an obvious infrastructure reason for this.

**Comment by jensjoha** [comment]
It crashes when it tries to verify. It does so because, as it loads, it finds an inconsistency in the NNBD settings, (one crash) as an example:
- SDK is in weak mode
- async-2.5.0-nullsafety.1 is compiled with nnbd disabled
- (and other ones)
- Then it tries to load flutter_test which is compiled with nndd strong => it tries to combined disabled and strong and *boom*.

Obviously it should have complained when trying to compile it as well.
And also, probably the sdk should have been compiled as agnostic (test setup I think)

I'll look into these points.

(There's also sort of an infra bug because it doesn't show the logs.json file which contains a stacktrace which would have been usefull I guess.)

**Comment by jensjoha** [comment]
https://dart-review.googlesource.com/c/sdk/+/168482 will fix at least some of this.

**Comment by leafpetersen** [comment]
Thanks @jensjoha . @jakemac53 FYI.

**Comment by leafpetersen** [comment]
I'm still seeing this [bot as purple](https://ci.chromium.org/p/dart/builders/try/flutter-frontend-try/435?).

**Comment by athomas** [comment]
I believe this is an infra failure again. I'll try to reproduce locally and restarted the tryjob. I suspect this happens while there are DEPS changes on master or the CL that haven't rolled to flutter, yet. The DEPS change probably has rolled since. The script doesn't create a full triple headed checkout, and there is still something missing.

**Comment by jensjoha** [comment]
Isn't it just the same thing again? Because my CL hadn't landed yet (12 hours ago)...

**Comment by athomas** [comment]
Could be, but there's also an issue with DEPS upgrade script visible in the logs. Though we might want to remove this completely, because flutter-frontend doesn't even `gclient sync`.

**Comment by leafpetersen** [comment]
This try bot is green with my CL so closing this out.  Feel free to re-open if you think there's more to be done here.  Thanks all!
