### ISSUE TITLE
[dart2js] dart2js unit tests need updating for null safety release

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#43816]
I'm tracking down failures with the [flag flip CL](https://dart-review.googlesource.com/c/sdk/+/166790), and I'm seeing some dart2js failures.  It looks to me like dart2js is being called programmatically with a string representing a dart program, which has no language version associated with it.  See for example:

pkg/compiler/test/codegen/builtin_interceptor_test

Either these program snippets need to have language version markers, or probably better the compiler needs to be called with an appropriate language version established. 

cc @sigmundch @munificent @franklinyow

**Comment by sigmundch** [comment]
@rakudrama @joshualitt have recently been migrating some of these tests so that we don't encode them in strings, but in .dart files directly. So my guess is that we'd eventually want the language version on each test.  Stephen/Joshua WDYT?

Given that the flag flip is time sensitive, we want a short-term fix first before we finish the migration the tests, though.

Here is a link to some of the failures: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8866337328791369232/+/steps/test_results/0/logs/new_test_failures__logs_/0

**Comment by rakudrama** [comment]
I'll take a look at some of these later today.

**Comment by rakudrama** [comment]
Joshua is working on this

**Comment by joshualitt** [comment]
This should now be fixed on TOT, see https://dart-review.googlesource.com/c/sdk/+/168141

**Comment by leafpetersen** [comment]
I'm still seeing some failures 
 - [here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865875139184400368/+/steps/test_results/0/logs/new_test_failures__logs_/0) 
  - [here](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8865875139184400352/+/steps/test_results/0/logs/new_test_failures__logs_/0)

The latter may not be a dart2js issue, I'm not sure.  Feel free to ping it back to me if you think not.

**Comment by sigmundch** [comment]
I believe the first one will require removing this line: https://github.com/dart-lang/sdk/blob/master/pkg/compiler/test/codegen/data/tdiv1.dart#L5 together with your CL.

Joshua initially was removing that when he tested the combined CL, but couldn't land it separately (currently analyzer needs it to opt-in the file to null-safety, once the default flips, the comment wont be needed anymore).

The latter seems to be outside dart2js, but more likely a setup in how observatory is built and tested?

**Comment by leafpetersen** [comment]
> I believe the first one will require removing this line: https://github.com/dart-lang/sdk/blob/master/pkg/compiler/test/codegen/data/tdiv1.dart#L5 together with your CL.
> 
> Joshua initially was removing that when he tested the combined CL, but couldn't land it separately (currently analyzer needs it to opt-in the file to null-safety, once the default flips, the comment wont be needed anymore).

I'm guessing it needs to be changed to 2.12 rather than removed - the whole package is opted out, but this test needs to be opted in, right?  That won't change after the experiment.

> The latter seems to be outside dart2js, but more likely a setup in how observatory is built and tested

I'll look into it.

**Comment by leafpetersen** [comment]
Tests pass locally with that file updated to 2.12, and I filed [this](https://github.com/dart-lang/sdk/issues/43881) issue to track the observatory_ui failure, so closing this one out.  Thanks all!
