### ISSUE TITLE
Debugger breaks in wrong place with sync* generator functions 

### ISSUE THREAD

**Issue by tomgilder** [dart-lang/sdk#45309]
Sometimes when using `sync*` generator functions, the debugger doesn't correctly break on breakpoints.

To reproduce:
1. Create a new Flutter app (standard new app template)
2. Put a breakpoint in Flutter framework on `Page`’s `canUpdate` method - line 591 in navigator.dart
3. Ensure debugging SDK is turned on
4. Run app for debugging 

Expected results: debugger pauses on line 591.

Actual results: debugger pauses on line 3731, the `_allRouteOverlayEntries sync*` getter.

<img width="555" alt="Screenshot 2021-03-14 at 17 32 35" src="https://user-images.githubusercontent.com/756862/111074370-45e8d580-84eb-11eb-9dc7-1b0caf18d265.png"><img width="678" alt="Screenshot 2021-03-14 at 17 32 02" src="https://user-images.githubusercontent.com/756862/111074341-323d6f00-84eb-11eb-9b0a-8ea193f03e03.png">

This isn't the only instance I've seen of this, I'll try to come up with an even simpler reproduction.

This happens with latest Flutter stable (Dart version 2.12.1) and Flutter dev, with VSCode and Android Studio on macOS, and running on both the iOS Simulator and Android Emulator.

**Comment by a-siva** [comment]
//cc @bkonyi

**Comment by bkonyi** [comment]
Resolved in https://github.com/dart-lang/sdk/commit/cd1f4c45606dfd6ca7bfd81b2dd66a9fd03deea7.

**Comment by tomgilder** [comment]
Thank you so much @bkonyi - I've been running into this every week, you've just made my life much easier 😁

**Comment by Oleksa3** [comment]
I still have this issue with Dart 2.14.2 (stable). Should it be already resolved in that version?
