### ISSUE TITLE
Analyzer plugin is removed from registered plugins after some time

### ISSUE THREAD

**Issue by incendial** [dart-lang/sdk#45994]
I've recently noticed that our analyzer plugin is getting unregistered (Plugins tab shows `No known analysis plugins.`) from a list of plugins after some time (like, ~20-60 seconds). I've tried different approaches with commenting code and checking logs, but none of them helped to clarify, what's wrong. It's probably connected with the integration part, because we have a cli that reuses the same codebase to collect issues and it works fine.

To reproduce this behaviour clone [Dart Code Metrics master branch,](https://github.com/dart-code-checker/dart-code-metrics) replace the `dart_code_metrics` dependency in `tools/analyzer_plugin` to a path dependency with the absolute path and reload the analysis server.

The only thing that I'm suspicious right now is `part / part of` directives, because the problem began when we started to use them in our codebase and we caught an exception in a file from different project (which has `part` directive in it as well):
```
1620804105768:Res:{"method"::"textDocument/publishDiagnostics","params"::{"uri"::"file::///Users/krutskikh/Development/lib/modules/inbox/models/dto/inbox_message_list_dto.dart","diagnostics"::[]},"jsonrpc"::"2.0"}
1620804105783:PluginEx:type 'Null' is not a subtype of type 'FutureOr<File>':#0      _FutureListener.handleError (dart::async/future_impl.dart::172::20)
#1      Future._propagateToListeners.handleError (dart::async/future_impl.dart::719::47)
#2      Future._propagateToListeners (dart::async/future_impl.dart::740::24)
#3      Future._completeWithValue (dart::async/future_impl.dart::542::5)
#4      Future._asyncCompleteWithValue.<anonymous closure> (dart::async/future_impl.dart::580::7)
#5      _microtaskLoop (dart::async/schedule_microtask.dart::40::21)
#6      _startMicrotaskLoop (dart::async/schedule_microtask.dart::49::5)
#7      _runPendingImmediateCallback (dart::isolate-patch/isolate_patch.dart::120::13)
#8      _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::185::5)
```
Maybe the initial problem and the exception are not connected.

Could you please help investigate this problem? I'm running out of ideas.

* Dart SDK version: 2.12.4 (stable) (Thu Apr 15 12:26:53 2021 +0200) on "macos_x64"
* MacOSX
* LSP is disabled
* VS Code extension 3.22

Note, that exception was caught with enabled LSP and SDK 2.14.0-48.0.dev.

**Comment by bwilkerson** [comment]
I haven't had time to look at this yet, but I'll note that this looks like an exception that was fixed by https://dart-review.googlesource.com/c/sdk/+/197600. It would be useful to know whether that change fixes the exception you're seeing. (The bug was introduced while migrating the analyzer to null safety and wasn't caught until we'd migrated the analysis server so that it could run in full null safety mode.)

**Comment by incendial** [comment]
Tested the plugin unregistration problem with 2.14.0-90 sdk and the problem is still there. Same goes for the exception (but it was tested with 2.14.0-108).

**Comment by incendial** [comment]
Sorry for pinging, but is there any chance you can take a look?

**Comment by devoncarew** [comment]
Two questions:

- the exception above (w/ the associated CL) was in the analyzer's file watching code and its error handling. Does your plugin do any file watching? If so, it may have this same issue when converted to null safety (you hit an error at runtime when package:watcher tries to report a file watch error)
- the fix in package:analyzer might not yet be in a published version; the fix landed ~23 days ago (https://github.com/dart-lang/sdk/commit/0e5d8d7c7b2e44fce3251714aa12a71b9beb7b80), but I don't believe we've published an analyzer version since then

**Comment by incendial** [comment]
Sorry for the delay, migrating to 1.7.0 `package:analyzer` version and clearing `.plugin_manager` helped (although I didn't checked the problem with 1.6, maybe it was solved earlier). Thank you for the fix!

While migrating to the new version I've noticed that we use a lot of implementation imports and tried to remove as much as possible. Three cases left so far:
1. `AnalysisDriverGeneric` is required if we override `createAnalysisDriver` from `ServerPlugin` and I don't see a way to import it without src imports.
2. We create driver from context, but `DriverBasedAnalysisContext` is not exported publicly. Is there a better way to create a driver with AnalysisContext?
```dart
AnalysisDriverGeneric createAnalysisDriver(plugin.ContextRoot contextRoot) {
    final rootPath = contextRoot.root;
    final locator = ContextLocator(resourceProvider: resourceProvider)
        .locateRoots(
            includedPaths: [rootPath],
            excludedPaths: contextRoot.exclude,
            optionsFile: contextRoot.optionsFile);

    if (locator.isEmpty) {
      ...
    }

    final builder = ContextBuilder(resourceProvider: resourceProvider);
    final context = builder.createContext(contextRoot: locator.first)
        as DriverBasedAnalysisContext;
    final dartDriver = context.driver;
```
3. We use `AnalysisOptionsProvider(driver.sourceFactory).getOptionsFromFile(file)` to convert optionsFile to YamlMap. Is there any other way to do it?

Could you please help with this? The initial problem is resolved, so I can create a separate issue if it's more convenient.

**Comment by bwilkerson** [comment]
@scheglov Have we converted `analyzer_plugin` to use `AnalysisContextCollection`?

**Comment by scheglov** [comment]
I don't think so, I see that `class ServerPlugin` has `AnalysisDriverGeneric createAnalysisDriver(ContextRoot contextRoot)`.

**Comment by bwilkerson** [comment]
@incendial

The plan is to move all analyzer clients over to using the class `AnalysisContextCollection` to create analysis contexts. The plugin protocol has an optimization in that it sends over the roots of the contexts that the server found, and that might cause a bit of a problem. I suspect that with `AnalysisContextCollection` that optimization is no longer needed, and we might eventually want to just send across the analysis roots and let plugins duplicate the discovery of context roots. That might not be strictly necessary in order to switch plugins over to the newer API, though. (I've never tested it, but it does seem to me that if we pass the context roots found by `AnalysisContextCollection` as analysis roots to a new `AnalysisContextCollection` that it ought to produce the same set of context roots.)

When that (unscheduled) arc of work is done plugins should theoretically not need to access internal classes.

> 1. `AnalysisDriverGeneric` is required if we override `createAnalysisDriver` from `ServerPlugin` ...

Why do you need to override `createAnalysisDriver`? I'm wanting to make sure we have the support you need in the new API.

> 3. We use `AnalysisOptionsProvider(driver.sourceFactory).getOptionsFromFile(file)` to convert `optionsFile` to `YamlMap`. Is there any other way to do it?

We don't appear to have any public API for that, but should probably consider adding one. I'd prefer having one place where the handling of the `include` key is done so that plugins don't get out of sync.

**Comment by incendial** [comment]
> Why do you need to override createAnalysisDriver? I'm wanting to make sure we have the support you need in the new API.

Basically, we create a driver, then subscribe to added and changed files `results` (which is `Stream<ResolvedUnitResult>`) and then process `ResolvedUnitResult`. Then we `sendNotification` to the server with `AnalysisErrorsParams` calculated from the resolved unit. And use the same driver to handle `handleEditGetFixes`.

Does `AnalysisContextCollection` handle file content that is edited in IDE (ex. VS Code), but not yet saved?

> We don't appear to have any public API for that, but should probably consider adding one. I'd prefer having one place where the handling of the include key is done so that plugins don't get out of sync.

Okay, then we'll stick with `AnalysisOptionsProvider`, but that'd definitely great to have.

**Comment by bwilkerson** [comment]
> Does `AnalysisContextCollection` handle a file content that is edited in IDE (ex. VS Code), but not yet saved?

You can pass in the `ResourceProvider` when you create the collection, and we're using an `OverlayResourceProvider` in server to handle those cases.

**Comment by incendial** [comment]
Oh, thanks for sharing this and the plan above.

If contexts from `AnalysisContextCollection` support subscribing to file changes and can prioritise currently open files analysis over all files analysis, then it seems that all our cases are covered.

**Comment by bwilkerson** [comment]
I don't believe that _any_ analysis context does those things. In server the file watcher is separate and needs to inform the driver when a file has changed. We need to add some public API to support that use case. The analysis driver is also the object that needs to be told which files are priority files (because it does the scheduling of work). That support also isn't part of the public API yet.

**Comment by bwilkerson** [comment]
@scheglov @devoncarew for visibility

**Comment by incendial** [comment]
> The analysis driver is also the object that needs to be told which files are priority files (because it does the scheduling of work). That support also isn't part of the public API yet.

Oh, right, we have some code to set `priorityFiles` for the driver. So, this looks important for new API to have something similar.

**Comment by incendial** [comment]
Haven't seen this issue in a while + all my questions were answered, thank you!
