### ISSUE TITLE
LateInitializationError: Field 'annotationAst' has not been initialized, when annotation in a TypeName.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#46103]
```dart
const a = 0;
List<void Function(@a int b)> foo() => [];
```

The issue is that `ResolverVisitor.visitTypeName()` does nothing. I guess that is because there were no annotations possible there before. But we have `GenericFunctionType` now, and it can have annotations on parameters.

```
  LateInitializationError: Field 'annotationAst' has not been initialized.
  #0      ElementAnnotationImpl.annotationAst (package:analyzer/src/dart/element/element.dart)
  #1      ConstantEvaluationEngine.computeDependencies (package:analyzer/src/dart/constant/evaluation.dart:338:30)
  #2      _ConstantWalker._computeDependencies (package:analyzer/src/dart/constant/compute.dart:75:22)
  #3      _ConstantNode.computeDependencies (package:analyzer/src/dart/constant/compute.dart:43:19)
  #4      Node.getDependencies (package:analyzer/src/summary/link.dart:148:40)
  #5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:53:40)
  #6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:119:18)
  #7      computeConstants (package:analyzer/src/dart/constant/compute.dart:26:14)
  #8      LibraryAnalyzer._computeConstants (package:analyzer/src/dart/analysis/library_analyzer.dart:250:5)
  #9      LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:135:5)
  #10     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:103:12)
  #11     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1626:63)
```

**Comment by NaarGes** [comment]
Hi, I'm facing same issue here
did you solve this?

**Comment by scheglov** [comment]
I thought that I did.
If you still seeing this, can you provide a test case on which in can be reproduced?

**Comment by NaarGes** [comment]
Sorry I couldn't send you the project because it wasn't for myself and I couldn't reproduce the error.
BTW the problem was solved after upgrading flutter to 2.5.1
Thank you

**Comment by scheglov** [comment]
Actually, it seems that the original issue was still happening.
I think this CL will fix it.
https://dart-review.googlesource.com/c/sdk/+/214101
