### ISSUE TITLE
Using absolute URI for web crashes dart compiler if it is a linux style path

### ISSUE THREAD

**Issue by annagrin** [dart-lang/sdk#47829]
Parent issue in flutter: https://github.com/flutter/flutter/issues/70305

It looks like `strongComponents.moduleAssignment` https://github.com/dart-lang/sdk/blob/e995cb5f7cd67d39c1ee4bdbe95c8241db36725f/pkg/frontend_server/lib/src/javascript_bundle.dart#L117 contains a malformed moduleUri `package:/Users/jonahwilliams/Documents/flutter/examples/hello_world/lib/a.dart`. I am not sure what causes it, need to investigate.

**Example code**

```dart
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/widgets.dart';
import '/Users/jonahwilliams/Documents/flutter/examples/hello_world/lib/a.dart';

void main() =>
  runApp(
    const Center(
      child:
        Text('Hello, world!',
          key: Key('title'),
          textDirection: TextDirection.ltr
        )
      )
    );
```
**Compilation output**

```
Error: Invalid package URI 'package:/Users/jonahwilliams/Documents/flutter/examples/hello_world/lib/a.dart':
  Invalid argument (packageUri): Package URIs must not start with a '/': Instance of '_Uri'.
lib/main.dart:6:8: Error: Not found: 'package:/Users/jonahwilliams/Documents/flutter/examples/hello_world/lib/a.dart'
import '/Users/jonahwilliams/Documents/flutter/examples/hello_world/lib/a.dart';
       ^                                                                
Unhandled exception:                                                    
Invalid argument (packageUri): Package URIs must not start with a '/': Instance of '_Uri'
#0      checkValidPackageUri (package:package_config/src/util.dart:71:5)
#1      SimplePackageConfig.resolve (package:package_config/src/package_config_impl.dart:131:23)
#2      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:159:45)
<asynchronous suspension>                                               
#3      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:628:5)
<asynchronous suspension>                                               
#4      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:541:9)
<asynchronous suspension>                                               
#5      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1100:11)
<asynchronous suspension>                                               
the Dart compiler exited unexpectedly.      
```

**Comment by lrhn** [comment]
The `Uri` class was changed some time ago (2.13.0) to actively prevent creating such a URI.

If the `import "/Users/....";` path is resolved against a current library URI which is a `package:` URI like `package:pkgname/something`, then the result should now be `package:pkgname/Users/...`.  Before that change, it would have created `package:/Users/...`.

So, whichever code created the `package:/Users/...` URI either used an old SDK, or it's not using the `Uri` class. (Or there is a bug in the `Uri` class, but that's unpossible!)

**Comment by annagrin** [comment]
@lrhn i need to confirm that the bug still reproduces, but if it does, it would be somewhere in the frontend server.
