### ISSUE TITLE
Compiler crash: Iterables do not have same length.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/sdk#48148]
```
Crash when compiling ... .
at character offset null:
Invalid argument(s): Iterables do not have same length.
#0      MapBase._fillMapWithIterables (dart:collection/maps.dart:92:7)
#1      new LinkedHashMap.fromIterables (dart:collection/linked_hash_map.dart:126:13)
#2      findTypeArgumentIssues (package:kernel/src/bounds_checks.dart:385:11)
#3      SourceLibraryBuilder.checkBoundsInType (package:front_end/src/fasta/source/source_library_builder.dart:3987:38)
#4      BodyBuilder._unaliasTypeAliasedConstructorInvocations (package:front_end/src/fasta/kernel/body_builder.dart:1389:22)
#5      BodyBuilder.performBacklogComputations (package:front_end/src/fasta/kernel/body_builder.dart:889:5)
#6      BodyBuilder.finishFields (package:front_end/src/fasta/kernel/body_builder.dart:877:5)
#7      DietListener._parseFields (package:front_end/src/fasta/source/diet_listener.dart:1010:17)
#8      DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:832:5)
#9      DietListener.endTopLevelFields (package:front_end/src/fasta/source/diet_listener.dart:376:5)
#10     Parser.parseFields (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2949:18)
#11     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2839:12)
#12     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:509:16)
#13     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:377:15)
#14     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:826:14)
<asynchronous suspension>
#15     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:388:9)
<asynchronous suspension>
#16     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:548:7)
<asynchronous suspension>
#17     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#18     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:162:19)
<asynchronous suspension>
#19     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#20     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:12)
<asynchronous suspension>
#21     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:10)
<asynchronous suspension>
#22     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:97:11)
<asynchronous suspension>
#23     SingleShotCompilerWrapper.compileInternal (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:398:11)
<asynchronous suspension>
#24     Compiler.compile.<anonymous closure> (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:216:45)
<asynchronous suspension>
#25     _processLoadRequest (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:886:37)
<asynchronous suspension>


#0      MapBase._fillMapWithIterables (dart:collection/maps.dart:92:7)
#1      new LinkedHashMap.fromIterables (dart:collection/linked_hash_map.dart:126:13)
#2      findTypeArgumentIssues (package:kernel/src/bounds_checks.dart:385:11)
#3      SourceLibraryBuilder.checkBoundsInType (package:front_end/src/fasta/source/source_library_builder.dart:3987:38)
#4      BodyBuilder._unaliasTypeAliasedConstructorInvocations (package:front_end/src/fasta/kernel/body_builder.dart:1389:22)
#5      BodyBuilder.performBacklogComputations (package:front_end/src/fasta/kernel/body_builder.dart:889:5)
#6      BodyBuilder.finishFields (package:front_end/src/fasta/kernel/body_builder.dart:877:5)
#7      DietListener._parseFields (package:front_end/src/fasta/source/diet_listener.dart:1010:17)
#8      DietListener.buildFields (package:front_end/src/fasta/source/diet_listener.dart:832:5)
#9      DietListener.endTopLevelFields (package:front_end/src/fasta/source/diet_listener.dart:376:5)
#10     Parser.parseFields (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2949:18)
#11     Parser.parseTopLevelMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2839:12)
#12     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:509:16)
#13     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:377:15)
#14     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:826:14)
<asynchronous suspension>
#15     SourceLoader.buildBodies (package:front_end/src/fasta/source/source_loader.dart:388:9)
<asynchronous suspension>
#16     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:548:7)
<asynchronous suspension>
#17     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#18     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:162:19)
<asynchronous suspension>
#19     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#20     generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:50:12)
<asynchronous suspension>
#21     generateKernel (package:front_end/src/kernel_generator_impl.dart:49:10)
<asynchronous suspension>
#22     kernelForModule (package:front_end/src/api_prototype/kernel_generator.dart:97:11)
<asynchronous suspension>
#23     SingleShotCompilerWrapper.compileInternal (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:398:11)
<asynchronous suspension>
#24     Compiler.compile.<anonymous closure> (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:216:45)
<asynchronous suspension>
#25     _processLoadRequest (file:///opt/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:886:37)
<asynchronous suspension>
```

```dart

const HInvalid invalidExample = HInvalidComposite(
  [
    HInvalidLeaf(0),
    HInvalidChild(
      HInvalidLeaf(0),
    ),
    HInvalidError("error message"),
  ],
);

typedef HInvalid = HBase<HKindInvalid>;
typedef HInvalidComposite<CHILD extends HInvalid> = HBaseComposite<HKindInvalid, CHILD>;
typedef HInvalidChild<CHILD extends HInvalid> = HBaseChild<HKindInvalid, CHILD>;
typedef HInvalidLeaf = HBaseLeaf<HKindInvalid>;
typedef HInvalidError = HBaseError<HKindInvalid>;

abstract class HBase<HKT extends HKind> implements Kind<HKT> {}

class HBaseComposite<HKT extends HKindValid, CHILD extends HBase<HKT>> implements HBase<HKT> {
  final List<CHILD> children;

  const HBaseComposite(
    final this.children,
  );
}

class HBaseChild<HKT extends HKindValid, CHILD extends HBase<HKT>> implements HBase<HKT> {
  final CHILD child;

  const HBaseChild(
    final this.child,
  );
}

class HBaseLeaf<HKT extends HKindValid> implements HBase<HKT> {
  final int data;

  const HBaseLeaf(
    final this.data,
  );
}

class HBaseError<HKT extends HKindInvalid> implements HBase<HKT> {
  final String errorMessage;

  const HBaseError(
    final this.errorMessage,
  );
}

abstract class Kind<HKT extends HKind> {}

abstract class HKind {}

abstract class HKindValid implements HKind {}

abstract class HKindInvalid implements HKindValid {}
```

**Comment by Pranav2907** [comment]
Can i get the whole project if possible?

**Comment by Pranav2907** [comment]
I guess the problem is in the abstraction of classes they are not properly extended .

**Comment by modulovalue** [comment]
> Can i get the whole project if possible?

The given example is self-contained and reproduces the crash. It isn't necessary to add a main function, just paste the example into an example.dart file and try to run it with `dart example.dart`

**Comment by Pranav2907** [comment]
okay , thank you I will try that.

**Comment by johnniwinther** [comment]
@modulovalue, I'm working on a fix. Your repo is sufficient. Thanks.

**Comment by Pranav2907** [comment]
hey can you help me understand what was the issu actually and how it was solved ? It seems hard to read from above given commit.

**Comment by johnniwinther** [comment]
The problem was caused by how the compiler builds the AST internally: 

We compile the AST in two phases. The first (outline phase) builds the library scopes with for instance field and method declarations with their declared types. The second (body phase) builds the initializers of field declarations and bodies of method declarations.

Because of modular compilation (used for instance for the web development compiler) some parts of the body phase work must be performed during the outline phase. Amongst these is building the initializer of constant fields, like `invalidExample` in the repo. Unfortunately, this work cannot easily be skipped in the body phase, meaning that we for instance build the AST for constant field initializers twice, both in the outline phase and in the body phase. 

In the latter, the duplicate ASTs are generally discarded, but in this case, the constructor invocation for `HInvalidChild(...)` inside `invalidExample` was not fully discarded, but left in an incomplete state, which triggered the crash. The fix was to detect the inconsistent state (in the code by checking the `.hasBeenInferred` property) and discard the invocation node at this point.

**Comment by burekas7** [comment]
Is there any solution for that? (Flutter 3.13)
I also have this problem. It happens after a specific api call, immediately after the response is arrived.

**Comment by Lonyless** [comment]
> Is there any solution for that? (Flutter 3.13) I also have this problem. It happens after a specific api call, immediately after the response is arrived.
> 
> EDITED: Updating from: `sdk: '>=3.0.3 <4.0.0'` To: `sdk: '>=3.1.0 <4.0.0'` Fixed the error.

same here, after trying to evaluate a dio response. Increasing sdk boundaries dont seem to have any effect

Unhandled exception:
Invalid argument(s): Iterables do not have same length.
#0      MapBase._fillMapWithIterables (dart:collection/maps.dart:178:7)
#1      new LinkedHashMap.fromIterables (dart:collection/linked_hash_map.dart:246:13)
#2      Substitution.fromPairs (package:kernel/type_algebra.dart:263:13)
#3      InferenceVisitorBase.getGetterTypeForMemberTarget (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1465:35)
#4      InstanceAccessTarget.getGetterType (package:front_end/src/fasta/type_inference/object_access_target.dart:489:30)
#5      InferenceVisitorImpl._computePropertyGet (package:front_end/src/fasta/type_inference/inference_visitor.dart:6663:36)
#6      InferenceVisitorImpl.visitPropertyGet (package:front_end/src/fasta/type_inference/inference_visitor.dart:7672:61)
#7      PropertyGet.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:2984:20)
#8      InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:257:27)
#9      InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:291:40)
#10     InferenceVisitorImpl.visitReturnStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:7894:11)
#11     ReturnStatement.accept (package:kernel/ast.dart:10127:43)
#12     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:242:26)
#13     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:198:17)
#14     BodyBuilder.parseSingleExpression (package:front_end/src/fasta/kernel/body_builder.dart:1780:62)
#15     SourceLoader.buildExpression (package:front_end/src/fasta/source/source_loader.dart:1320:21)
<asynchronous suspension>
#16     IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:2033:39)
<asynchronous suspension>
#17     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:1853:12)
<asynchronous suspension>
#18     FrontendCompiler.compileExpression (package:frontend_server/frontend_server.dart:981:28)
<asynchronous suspension>
#19     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1452:11)

doctor:

[√] Flutter (Channel stable, 3.13.1, on Microsoft Windows [versÆo 10.0.19045.3324], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.3)
[√] Android Studio (version 2022.2)
[√] VS Code, 64-bit edition (version 1.81.1)
[√] Connected device (4 available)
[√] Network resources

**Comment by modulovalue** [comment]
@burekas7 @Craftplacer @Lonyless I think you should consider opening a new issue.

**Comment by burekas7** [comment]
@Lonyless 
Maybe it's the same error but a different reason.
For me, updating the sdk fixed it.

**Comment by johnniwinther** [comment]
@burekas7 @Craftplacer @Lonyless The stack traces are different enough to indicate that this is a new problem, so do create a new issue. Also, if you can create a repro it would be of much help.

**Comment by fedpinx** [comment]
In my case it's happening even with` sdk: '>=3.1.0 <4.0.0'`, and its happening only in Debug mode, and when I'm trying to access a dynamic object inside a Response (Dio).

**Comment by johnniwinther** [comment]
The new problem (crash originating from `SourceLoader.buildExpression`) is tracked in #53453

@fedpinx Thanks for the additional info on the circumstances for the crash.

**Comment by pv-kashif** [comment]
> Is there any solution for that? (Flutter 3.13) I also have this problem. It happens after a specific api call, immediately after the response is arrived.
> 
> EDITED: Updating from: `sdk: '>=3.0.3 <4.0.0'` To: `sdk: '>=3.1.0 <4.0.0'` Fixed the error.

same error after upgrading to flutter 3.13 in same use case like u...

**Comment by Chandio763** [comment]
> In my case it's happening even with` sdk: '>=3.1.0 <4.0.0'`, and its happening only in Debug mode, and when I'm trying to access a dynamic object inside a Response (Dio).

Same, happening exact after the responce of an api using dio.
upgrading version to   sdk: '>=3.1.0 <4.0.0' somehow fixed it but I am using breakpoint to view responce, this exceptions happens most of the time.

**Comment by 2p31-1** [comment]
same here after upgrading flutter 3.13.3, dart 3.1.1

**Comment by Chandio763** [comment]
> same here after upgrading flutter 3.13.3, dart 3.1.1

unchecking the unhandled exception in vs code works for me but i think this isn't the solution bcz we need to track unhandled exceptions.

**Comment by johnniwinther** [comment]
The issue has been fixed (see https://github.com/dart-lang/sdk/issues/53453) and is available in the current dev release and will be available in the next beta and stable releases.

**Comment by faisalansari0367** [comment]
> I see the same issue occur on Dart 3.2.0 (build 3.2.0-65.0.dev) (with Flutter) while debugging when trying to read a value by hovering over a property in IDEA.

Same issue is happening with me when I am trying to debug the repsonse of an API.
following are the details with a screenshot for the same.

Unhandled exception:
Invalid argument(s): Iterables do not have same length.
#0      MapBase._fillMapWithIterables (dart:collection/maps.dart:178:7)
#1      new LinkedHashMap.fromIterables (dart:collection/linked_hash_map.dart:246:13)
#2      Substitution.fromPairs (package:kernel/type_algebra.dart:263:13)
#3      InferenceVisitorBase.getGetterTypeForMemberTarget (package:front_end/src/fasta/type_inference/inference_visitor_base.dart:1465:35)
#4      InstanceAccessTarget.getGetterType (package:front_end/src/fasta/type_inference/object_access_target.dart:489:30)
#5      InferenceVisitorImpl._computePropertyGet (package:front_end/src/fasta/type_inference/inference_visitor.dart:6663:36)
#6      InferenceVisitorImpl.visitPropertyGet (package:front_end/src/fasta/type_inference/inference_visitor.dart:7672:61)
#7      PropertyGet.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:2984:20)
#8      InferenceVisitorImpl._inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:257:27)
#9      InferenceVisitorImpl.inferExpression (package:front_end/src/fasta/type_inference/inference_visitor.dart:291:40)
#10     InferenceVisitorImpl.visitReturnStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:7894:11)
#11     ReturnStatement.accept (package:kernel/ast.dart:10127:43)
#12     InferenceVisitorImpl.inferStatement (package:front_end/src/fasta/type_inference/inference_visitor.dart:242:26)
#13     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:198:17)
#14     BodyBuilder.parseSingleExpression (package:front_end/src/fasta/kernel/body_builder.dart:1780:62)
#15     SourceLoader.buildExpression (package:front_end/src/fasta/source/source_loader.dart:1320:21)
<asynchronous suspension>
#16     IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:2033:39)
<asynchronous suspension>

#17     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:1853:12)
<asynchronous suspension>
#18     FrontendCompiler.compileExpression (package:frontend_server/frontend_server.dart:981:28)
<asynchronous suspension>
#19     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1452:11)
<asynchronous suspension>

the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
Exited (1)



flutter doctor output:
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.4.1 22F770820d darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

<img width="1189" alt="Screenshot 2023-09-30 at 5 33 38 PM" src="https://github.com/dart-lang/sdk/assets/61263149/c6bf9ccd-ab63-49e5-bfc6-0230341d440a">

**Comment by jaypathak9460** [comment]
Yes i have faced same error after upgrading Flutter version 
once it shows me error to update the compileSdkVersion so i did that but still facing same issue
i also update the
 environment:
  sdk: '>=3.1.2 <4.0.0'
i got the reference by creating new and then i copied this value from it but issue still persists.
 any help would be help full

**Comment by johnniwinther** [comment]
The fix was first included in [3.2.0-154.0.dev](https://github.com/dart-lang/sdk/releases/tag/3.2.0-154.0.dev) so it has not yet been picked up by the current Flutter version.

@christopherfujino Do you know when this can be expected to be picked up by Flutter?

**Comment by christopherfujino** [comment]
> The fix was first included in [3.2.0-154.0.dev](https://github.com/dart-lang/sdk/releases/tag/3.2.0-154.0.dev) so it has not yet been picked up by the current Flutter version.
> 
> @christopherfujino Do you know when this can be expected to be picked up by Flutter?

Not sure when exactly it rolled, but currently the engine is past that version, at 3.3.0-2.0.dev: https://github.com/flutter/engine/commit/429a242b0db60b887ff3aa906f525fda2f686bdd

**Comment by leqnam** [comment]
Ohmg I face this issue too when I am trying to debug the repsonse of an API.

```
[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.22621.2428], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.7.3)
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Ultimate Edition (version 2023.2)
[√] VS Code (version 1.83.1)
[√] Connected device (3 available)
[√] Network resources
```

**Comment by kashiflab** [comment]
@christopherfujino I am also facing this issue while fetching data from hive.

**Comment by hupo376787** [comment]
Same issue, but I upgrade my flutter solved.

```
flutter upgrade
Upgrading Flutter to 3.16.4 from 3.13.0 in D:\flutter\src\flutter...
```

**Comment by Caroline1224** [comment]
> In my case it's happening even with` sdk: '>=3.1.0 <4.0.0'`, and its happening only in Debug mode, and when I'm trying to access a dynamic object inside a Response (Dio).

How did you go around it please?
