### ISSUE TITLE
Analyzer error causing Invalid File Path in VS Code.

### ISSUE THREAD

**Issue by CalebQ42** [dart-lang/sdk#48203]
I was making some major changes to my Flutter app when I started to get an Invalid file path error in VS Code. In particular I removed an existing Widget and replaced it with a new one (EditableContents to EditContent) a now whenever I import the file (`ui/editable_common.dart`), VS Code starts throwing the error. I posted on https://github.com/Dart-Code/Dart-Code and they told me to post it here.

[Here](https://github.com/CalebQ42/SWAssistant/tree/ab672395391b242995da3e6ce7ae5d6dfa638932) is my project at the commit where I'm having the problem. In particular opening `ui/items/morality.dart` and `ui/items/obligations.dart` causes the error.

I am running on Arch Linux with dart version `2.16.0-134.1.beta`.

@DanTup said that this was the cause, though I've also attached the full log file:
```
1643027061620:Ex:Analysis failed:: /home/belac/Projects/SWAssistant/lib/ui/items/characters/obligations.dart context:: exception_20220124_062421_256
Invalid argument(s):: Tried to format an error using NamedTypeImpl
#0      ErrorReporter._convertElements (package::analyzer/error/listener.dart::158::9)
#1      ErrorReporter.reportErrorForOffset (package::analyzer/error/listener.dart::105::5)
#2      ErrorReporter.reportErrorForToken (package::analyzer/error/listener.dart::123::5)
#3      ErrorVerifier._checkMixinInference (package::analyzer/src/generated/error_verifier.dart::4714::31)
#4      ErrorVerifier._checkClassInheritance (package::analyzer/src/generated/error_verifier.dart::1291::7)
#5      ErrorVerifier.visitClassDeclaration (package::analyzer/src/generated/error_verifier.dart::447::9)
#6      ClassDeclarationImpl.accept (package::analyzer/src/dart/ast/ast.dart::1494::50)
#7      NodeListImpl.accept (package::analyzer/src/dart/ast/ast.dart::7813::20)
#8      CompilationUnitImpl.visitChildren (package::analyzer/src/dart/ast/ast.dart::2105::21)
#9      RecursiveAstVisitor.visitCompilationUnit (package::analyzer/dart/ast/visitor.dart::765::10)
#10     ErrorVerifier.visitCompilationUnit (package::analyzer/src/generated/error_verifier.dart::496::11)
#11     CompilationUnitImpl.accept (package::analyzer/src/dart/ast/ast.dart::2098::50)
#12     LibraryAnalyzer._computeVerifyErrors (package::analyzer/src/dart/analysis/library_analyzer.dart::485::10)
#13     LibraryAnalyzer.analyze.<anonymous closure> (package::analyzer/src/dart/analysis/library_analyzer.dart::149::7)
#14     _LinkedHashMapMixin.forEach (dart::collection-patch/compact_hash.dart::539::8)
#15     LibraryAnalyzer.analyze (package::analyzer/src/dart/analysis/library_analyzer.dart::148::11)
#16     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package::analyzer/src/dart/analysis/driver.dart::1455::63)
#17     PerformanceLog.run (package::analyzer/src/dart/analysis/performance_logger.dart::32::15)
#18     AnalysisDriver._computeAnalysisResult (package::analyzer/src/dart/analysis/driver.dart::1431::20)
#19     AnalysisDriver.performWork (package::analyzer/src/dart/analysis/driver.dart::1055::22)
#20     AnalysisDriverScheduler._run (package::analyzer/src/dart/analysis/driver.dart::2137::24)
```

[dartLog.log](https://github.com/Dart-Code/Dart-Code/files/7925549/dartLog.log)

**Comment by scheglov** [comment]
I believe this was fixed in edbf6300a13095e164a876ee33251ec91fea072f by removing the corresponding code.

**Comment by th0rgall** [comment]
I'm still seeing the same issue @scheglov. For me, it seems to be related to my usage of `on` in a `mixin`:

This works:

```
mixin Fruity {
  @override
  Widget build(BuildContext context) {
    return const Text("I'm a fruit");
  }
```

This leads to the invalid path error:
```
mixin Fruity on State<AbstractWidget> {
  @override
  Widget build(BuildContext context) {
    return const Text("I'm a fruit");
  }
}
```

I'm probably trying to use mixins for something they're not meant to be used (to override the build method), but the related error message could in that case be improved.

- [DartPad of the "working" sample](https://dartpad.dev/?id=ba8861b41a5241684eed80868bac0217) 
- [DartPad of the error sample](https://dartpad.dev/?id=199e8464c82c7dc869cb8b456de59aba), it produces an XMLHTTPRequest error in DartPad, which is probably equivalent to the Invalid file path on a local machine.

This is the output from my `dart.analyzerInstrumentationLogFile` when running the error sample in a fresh `flutter create` issue via VSCode, with the same error as the issue opener.

```
1651319686406:Res:{"method"::"$/progress","params"::{"token"::"ANALYZING","value"::{"kind"::"begin","title"::"Analyzing…"}},"jsonrpc"::"2.0"}
1651319686875:Ex:Analysis failed:: /Users/thor/Code/contrib/darterror/darterror/lib/main.dart context:: exception_20220430_135446_755
Invalid argument(s):: Tried to format an error using NamedTypeImpl
#0      ErrorReporter._convertElements (package::analyzer/error/listener.dart::158::9)
#1      ErrorReporter.reportErrorForOffset (package::analyzer/error/listener.dart::105::5)
#2      ErrorReporter.reportErrorForToken (package::analyzer/error/listener.dart::123::5)
#3      ErrorVerifier._checkMixinInference (package::analyzer/src/generated/error_verifier.dart::4714::31)
#4      ErrorVerifier._checkClassInheritance (package::analyzer/src/generated/error_verifier.dart::1291::7)
#5      ErrorVerifier.visitClassDeclaration (package::analyzer/src/generated/error_verifier.dart::447::9)
#6      ClassDeclarationImpl.accept (package::analyzer/src/dart/ast/ast.dart::1494::50)
#7      NodeListImpl.accept (package::analyzer/src/dart/ast/ast.dart::7813::20)
#8      CompilationUnitImpl.visitChildren (package::analyzer/src/dart/ast/ast.dart::2105::21)
#9      RecursiveAstVisitor.visitCompilationUnit (package::analyzer/dart/ast/visitor.dart::765::10)
#10     ErrorVerifier.visitCompilationUnit (package::analyzer/src/generated/error_verifier.dart::496::11)
#11     CompilationUnitImpl.accept (package::analyzer/src/dart/ast/ast.dart::2098::50)
#12     LibraryAnalyzer._computeVerifyErrors (package::analyzer/src/dart/analysis/library_analyzer.dart::485::10)
#13     LibraryAnalyzer.analyze.<anonymous closure> (package::analyzer/src/dart/analysis/library_analyzer.dart::149::7)
#14     _LinkedHashMapMixin.forEach (dart::collection-patch/compact_hash.dart::539::8)
#15     LibraryAnalyzer.analyze (package::analyzer/src/dart/analysis/library_analyzer.dart::148::11)
#16     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package::analyzer/src/dart/analysis/driver.dart::1455::63)
#17     PerformanceLog.run (package::analyzer/src/dart/analysis/performance_logger.dart::32::15)
#18     AnalysisDriver._computeAnalysisResult (package::analyzer/src/dart/analysis/driver.dart::1431::20)
#19     AnalysisDriver.performWork (package::analyzer/src/dart/analysis/driver.dart::1173::26)
#20     AnalysisDriverScheduler._run (package::analyzer/src/dart/analysis/driver.dart::2137::24)
<asynchronous suspension>
```

**Comment by scheglov** [comment]
Can you try any Dart SDK `2.17`? It looks that https://github.com/dart-lang/sdk/commit/edbf6300a13095e164a876ee33251ec91fea072f was included only into a couple of `2.16` builds, and probably did not go into the final build. In the bleeding edge codebase there is simply no `ErrorVerifier._checkMixinInference`, there is nothing to fix :-)

**Comment by th0rgall** [comment]
I'm indeed on Dart SDK 2.16.2. Since my issue is not urgent (I found a workaround), I made a note to try my error sample again once Flutter stable uses Dart 2.17+. I'll mention it here if the same issue persists (probably/hopefully not).
