### ISSUE TITLE
Completion shows global variable where hover shows a local field of the same name

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#52839]
When a class contains a field that also matches a global, the code completion shows the global version whereas the hover shows the local version:

<img width="899" alt="Screenshot 2023-07-03 at 23 25 41" src="https://github.com/dart-lang/sdk/assets/1078012/f976978b-2eb0-4ab6-9698-f6a30a174a10">

<img width="466" alt="Screenshot 2023-07-03 at 23 25 51" src="https://github.com/dart-lang/sdk/assets/1078012/2432a2fd-0298-4ced-8dd3-c790144229fa">

I think hover is correct and completion may be doing the wrong thing (@bwilkerson?) - however I'm not completely sure because I encountered this while testing what seemed like surprising behaviour in extension classes and unqualified access (see https://twitter.com/anaisbetts/status/1675961549339467776) where the global/top level field is being used over the instance one.

**Comment by DanTup** [comment]
> then we look in the enclosing library (including imported names), and finally we look in the supertypes of the class

Ah! I thought this behaviour was specific to extensions so had been looking there for an explanation. The spec clearly describes it where you noted (and gives some good reasoning). Thanks!

**Comment by keertip** [comment]
Cannot reproduce this issue, it appears to have fixed with the refactor of the completion code.

**Comment by DanTup** [comment]
@keertip my original repro still seems to still show the issue for me (on a bleeding-edge build):

![image](https://github.com/dart-lang/sdk/assets/1078012/0d27bb5c-593c-45c2-bab5-40d0d279ffde)

Although what wasn't visible in my screenshot above was that `dart:io` is already imported (I should've included a full copy/pastable repro!). Here's my complete file:

```dart
import 'dart:io';

class Foo {
  /// Local exitCode
  int get exitCode => 1;

  foo() {
    exit
  }
}
```

**Comment by keertip** [comment]
@DanTup , thanks! Yes, can reproduce the issue with the above example.

**Comment by keertip** [comment]
Something more on this. Noticed this was happening only with `exitCode` and not with other globals from `dart:io`. Looked at the source code and saw that `exitCode` has both a getter and a setter defined. If we do the same with the example, 

```
import 'dart:io';

class Foo {
  /// Local exitCode
  int get exitCode => 1;
  void set exitCode(int i) {}

  foo() {
    exitC // complete here
  }
}
```

then it completes with the local. In the previous example, the global getter was not suggested as it was shadowed by the local, it was the setter for `exitCode` that was being suggested in the completion.

**Comment by keertip** [comment]
Yes, that is right, we are using the name of the setter rather than display name.
