### ISSUE TITLE
RegExp is deprecated in dart

### ISSUE THREAD

**Issue by bambinoua** [dart-lang/sdk#62012]
I've upgraded flutter to 3.38.1 and now I have a many deprecation warnings for RegExp.

`RegExp is deprecated and shouldn't be used. This class will become 'final' in a future release. 'Pattern' may be a more appropriate interface to implement`

So how do I need to migrate from `RegExp` if `Pattern` is just interface?

It loos like a lint rule allows me to see such kind of deprecations and I would not like to disable it because I believe it disables all deprecation warnings.

**Comment by mraleph** [comment]
These deprecation warnings should only be showed when you extend or implement `RegExp`. Do you see these when you just _use_ `RegExp`?

**Comment by bambinoua** [comment]
Unfrotunately I see them on every `RegExp` I used, i.e.

```dart
static const _someRegExp = RegExp(r'...');
```

**Comment by FMorschel** [comment]
@mraleph, I've commented at https://github.com/dart-lang/sdk/issues/61214#issuecomment-3469369766 (and https://github.com/dart-lang/sdk/issues/55608#issuecomment-3470515962 and https://github.com/dart-lang/sdk/issues/60504#issuecomment-3470522777), this happens on completion.

Even `RegExp` specific members show as deprecated.

**Comment by mraleph** [comment]
@bambinoua can you post the full error/warning/lint you are getting? I can't repro this with simple usage.

@FMorschel 

> Even `RegExp` specific members show as deprecated.

Can you file separate issue for that? Sounds like a bad bug which should be at the very least P1 if not P0 given how core `RegExp` is.

**Comment by FMorschel** [comment]
> Can you file separate issue for that?

I've opened https://github.com/dart-lang/sdk/issues/62013 and pinged you.

**Comment by bambinoua** [comment]
@mraleph  
> can you post the full error/warning/lint you are getting? I can't repro this with simple usage.

I've posted the full message in a first topic. I.e. I saw the exact text which is provided by `Deprecate.implementation` annotation which is added to `RegExp` class in all places where the `RegExp` constructor is used.

**Comment by mraleph** [comment]
> I've posted the full message in a first topic.

I am interested in the message code (e.g. `deprecated_member_use`) which is part of the whole warning printed by the analyzer (or displayed in the IDE).

**Comment by FMorschel** [comment]
@bambinoua could you add a screenshot or something for what you mean? I've tested with Flutter 3.38.1 with VS Code, IntelliJ and running `dart analyze`, and I could not reproduce this.

**Comment by mraleph** [comment]
I am wondering if it is some other tool (e.g. custom_lint?) or something else (e.g. using outdated analyzer with newer core libs?) which displays these.

**Comment by bambinoua** [comment]
> [@bambinoua](https://github.com/bambinoua) could you add a screenshot or something for what you mean? 

I will do that tomorrow.

**Comment by bambinoua** [comment]
> deprecated_member_use

As I remember I saw this code.

**Comment by FMorschel** [comment]
> I am wondering if it is some other tool (e.g. custom_lint?) or something else (e.g. using outdated analyzer with newer core libs?) which displays these.

I'm not sure how you imagined this, but I did a simple empty project with the old `dart_code_metrics`, and I got no errors even though it uses the old plugin system, and it solved for `analyzer` v5.

Repro:

```dart
void f() {
  RegExp r;
}
```

**Comment by bambinoua** [comment]
Today I've upgraded flutter again and it looks like the issue gone. 🤷‍♂️
So I am closing this issue at the moment.

> I'm not sure how you imagined this,

@FMorschel  You understand that I didn't come up with this specially. ;)

> I am wondering if it is some other tool (e.g. custom_lint?) or something else (e.g. using outdated analyzer with newer core libs?)

@mraleph  Maybe. I use only `flutter_lints`.

**Comment by FMorschel** [comment]
> You understand that I didn't come up with this specially.

Sorry, the _you_ on that comment was @mraleph. I was referring to the way he imagined the diagnostic to be showing up.

**Comment by mraleph** [comment]
There is an indication that we can somehow get into a state where we report incorrect warnings, see https://github.com/dart-lang/sdk/issues/62013#issuecomment-3555304271

@scheglov do you have any hypothesis around how this can happen? I thought one possibility is that SDK is updated in place, which leads to core libraries being updated but analyzer process is still running from the older SDK, but I was not able to reproduce this. Maybe there are some other possibilities around caches in `~/.dartServer` getting skewed?

**Comment by scheglov** [comment]
@srawlins Can it be an issue with enhanced `Deprecated` handling?

**Comment by lrhn** [comment]
Most likely reason is running a version of  the analyzer that doesn't understand the enhanced deprecated.
That would see `@Deprecated.implementation()` on `class RegExp`, see that it's an instance of `Deprecated` without knowing that there is a `_kind` field to check, and report it as deprecated in general.

The question is how you run an older version of the analyzer against code using a newer SDK (containing a `Deprecated.implementation` declaration).

**Comment by scheglov** [comment]
Right, using an older version of the analyzer sounds as the best explanation to me.
Maybe actually Dart SDK was updated in place.

**Comment by srawlins** [comment]
> The question is how you run an older version of the analyzer against code using a newer SDK (containing a `Deprecated.implementation` declaration).

This is what I can't figure out...

**Comment by mraleph** [comment]
If you upgrade Flutter SDK while analysis server is running then you will end up in a situation where on-disk SDK is updated, but DAS process is using old version. However I was not able to trivially reproduce the problem by doing this though (probably because at that point core libraries were already parsed and DAS does not reparse them). So there might be something else going on.

**Comment by mehdi31075** [comment]
I faced the same issue after upgrading Flutter from 3.19.x to 3.39.x.
After reloading my IDE(invalidating caches), the issue has gone.

**Comment by FMorschel** [comment]
@mehdi31075 so you upgraded the SDK with the IDE open?

**Comment by plchekspend** [comment]
I’m facing the same issue. I’m using FVM for SDK management, and after switching from Flutter 3.35.7 to 3.38.3.
The warning still doesn’t go away, Even after reloading Android Studio or restarting the Dart analysis server, the warning persists.

`info: 'RegExp' is deprecated and shouldn't be used. This class will become 'final' in a future release. 'Pattern' may be a more appropriate interface to implement. (deprecated_member_use at lib/app/disbursement/admin/business/view/widgets/manually_add_business_dialog.dart:67) `

**Comment by FMorschel** [comment]
We recently had a report for another issue that happened to be a `puro` issue (https://github.com/dart-lang/sdk/issues/61857). Is everyone having this problem using `FVM`? I'm not familiar enough with it to know how it updates the SDK.

**Comment by nigow** [comment]
i had the exact same issue right after upgrading from 3.35.3 to 3.38.3. restarting my text editor (vscode) suppressed all the warnings.

**Comment by plchekspend** [comment]
> I’m facing the same issue. I’m using FVM for SDK management, and after switching from Flutter 3.35.7 to 3.38.3. The warning still doesn’t go away, Even after reloading Android Studio or restarting the Dart analysis server, the warning persists.
> 
> `info: 'RegExp' is deprecated and shouldn't be used. This class will become 'final' in a future release. 'Pattern' may be a more appropriate interface to implement. (deprecated_member_use at lib/app/disbursement/admin/business/view/widgets/manually_add_business_dialog.dart:67) `

It's look like the warnings goes away, since i start my mac after 2 days.

**Comment by artdedeco** [comment]
I'm also having this issue for some time now (I don't remember exactly when it started). Restarting VS Code did not fix it for me as it did for others. If it's any help, this is my `doctor` output:

```
[✓] Flutter (Channel stable, 3.38.2, on Microsoft Windows [Version 10.0.26200.7309], locale pt-BR) [213ms]
    • Flutter version 3.38.2 on channel stable at D:\sdk\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f5a8537f90 (2 weeks ago), 2025-11-18 09:27:21 -0500
    • Engine revision b5990e5ccc
    • Dart version 3.10.0
    • DevTools version 2.51.1
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android,
      enable-ios, cli-animations, enable-native-assets, omit-legacy-version-file, enable-lldb-debugging
```

The VS Code extension version is `3.124.1`.

I did update the SDK with VS Code open.

Is there anything I can check on my side to help investigate?

> We recently had a report for another issue that happened to be a `puro` issue ([#61857](https://github.com/dart-lang/sdk/issues/61857)). Is everyone having this problem using `FVM`? I'm not familiar enough with it to know how it updates the SDK.

@FMorschel As far as I know I'm not using FVM. I'm a bit new to flutter, so I'm not sure; In any way, if that's something you need to install/configure on top of how the SDK is installed by default with the VS Code extension (which is what I did), then I'd not be using that.

**Comment by FMorschel** [comment]
@andre-ss6, thanks!

> The VS Code extension version is `3.124.1`.

This is unnecessary because all the diagnostics are provided by the SDK, but thank you anyway!

> [I]f that's something you need to install/configure on top of how the SDK is installed by default with the VS Code extension (which is what I did), then I'd not be using that.

Yes, FVM stands for `Flutter Version Manager` (https://fvm.app/) and that would install the SDK for you instead of the VS Code extension. In any case, you still helped by letting us know this also happens with the default install.

**Comment by artdedeco** [comment]
Hmm, I just noticed I'm not seeing the warnings anymore -- maybe they _did_ go away with restarts or something -- but the "Intellisense"/autocomplete window still shows them crossed-out:

<img width="672" height="451" alt="Image" src="https://github.com/user-attachments/assets/a02aa79e-5306-4318-9f54-1b9b5c9d7d54" />

Also not sure if showing `(deprecated)` right before the type declaration in the rendered docs is intentional (given that only implementating it should be deprecated).

**Comment by FMorschel** [comment]
This has been fixed on a new patch (see https://github.com/dart-lang/sdk/issues/62013). If you run `flutter upgrade` on your terminal you should see your Dart version go to `3.10.3`, IIRC.

**Comment by YahefuYusufu** [comment]
Just update the Flutter to latest and clean the build will solve this warning.

**Comment by RakaAlrian** [comment]
i'm using flutter 3.41.6 (latest stable today) and get this warning, already do flutter clean and flutter pub get, the warning still exist. fyi, i'm using fvm with other flutter versions. please help, this warning is annoying

**Comment by srawlins** [comment]
@RakaAlrian can you file a new issue with your details, please? A minimal reproduction case is important to add.

**Comment by dedvalson** [comment]
I am seeing this with current stable version:

```
PS D:\Source\CoralVue\Master\Apps\hydros> flutter upgrade
Flutter is already up to date on channel stable
Flutter 3.41.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 00b0c91f06 (3 weeks ago) • 2026-04-29 10:03:19 -0700
Engine • hash 9161402dc0e134b3fb5adee5046b6e84b1a5e1c1 (revision 42d3d75a56) (19 days ago) • 2026-04-28 17:31:55.000Z
Tools • Dart 3.11.5 • DevTools 2.54.2
```

<img width="766" height="250" alt="Image" src="https://github.com/user-attachments/assets/57392331-4774-40b0-964e-e278293f3932" />

**Comment by FMorschel** [comment]
@dedvalson, does it also reproduce with this code if you put it on a new project or only for existing ones?

**Comment by dedvalson** [comment]
> [@dedvalson](https://github.com/dedvalson), does it also reproduce with this code if you put it on a new project or only for existing ones?

It does NOT reproduce in a new project, only in the existing one. 

flutter clean does not help.

**Comment by FMorschel** [comment]
@scheglov, any idea what could be triggering this?

**Comment by mraleph** [comment]
I think this goes away if people purge analysis cache, so it must be some sort of caching issue.

**Comment by dedvalson** [comment]
I did the following:

flutter clean
Exit IDE
deleted  .dartServer and all contents
Restart IDE
flutter pub get

Problem is still there. But only in my project, not new ones.  Any additional suggestions?

**Comment by dedvalson** [comment]
I cannot explain why this worked, but it did.

I backed flutter-lints from ^6.0.0 to ^5.0.0 and the problem went away.

I moved flutter-lints back to ^6.0.0 and the problem stayed away.

**Comment by FMorschel** [comment]
CC @bwilkerson, any idea why updating the list of enabled lints fixed this diagnostic?
