### ISSUE TITLE
`multiple_part_of_directives` triggering on a quick-fix needs a server restart to go away

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/sdk#62209]
I've tried making a smaller repro, but no luck yet. At least the case I have is under MIT, so we can use it.

1. Clone https://github.com/FMorschel/essential_lints/commit/2e5276526afdb24fd08ff37af0535d2cf7528d8c
2. Open `essential_lints_annotations\lib\src\sorting_members\sort_declarations.dart`
3. Add a `part 'foo.dart';` line
4. Use the `Create file 'foo.dart'` quick fix
5. See `multiple_part_of_directives` triggering on that file (even though there is only one)

Editing the file in any way doesn't make the diagnostic go away (removing the `part of` directive or adding new declarations). Restarting the server fixes it.

CC @scheglov

**Comment by DanTup** [comment]
hmm, the overlay on the server looks suspicious:

<img width="1030" height="274" alt="Image" src="https://github.com/user-attachments/assets/a2cee09b-0b66-43ef-b3c6-36c895644531" />

This makes me wonder if we've applied an edit incorrectly (perhaps in the LSP server) - I will take a look.

**Comment by DanTup** [comment]
The servers part of this actually looks correct - the LSP traffic is below. VS Code sends a `didOpen` request that says the file already has the content, and then it sends a `didChange` request that says to insert the text. This does not make any sense to me - I will try to repro in isolation.


```
1765278318564:Req: {
	"jsonrpc": "2.0",
	"id": 22,
	"method": "textDocument/codeAction",
	"params": {
		"textDocument": {
			"uri": "file:///D%3A/Dev/Temp%20Projects/essential_lints/essential_lints_annotations/lib/src/sorting_members/sort_declarations.dart"
		},
		// ...
	},
	"clientRequestTime": 1765278318564
}
1765278318566:Res: {
	"id": 22,
	"jsonrpc": "2.0",
	"result": [
		{
			"command": {
				"arguments": [
					{
						"action": "dart.fix.create.file"
					}
				],
				"command": "dart.logAction",
				"title": "Log Action"
			},
			"diagnostics": [],
			"edit": {
				"documentChanges": [
					{
						"kind": "create",
						"uri": "file:///D:/Dev/Temp%20Projects/essential_lints/essential_lints_annotations/lib/src/sorting_members/foo.dart"
					},
					{
						"edits": [
							{
								"newText": "part of 'sort_declarations.dart';\r\n\r\n",
								"range": {
									"end": {
										"character": 0,
										"line": 0
									},
									"start": {
										"character": 0,
										"line": 0
									}
								}
							}
						],
						"textDocument": {
							"uri": "file:///D:/Dev/Temp%20Projects/essential_lints/essential_lints_annotations/lib/src/sorting_members/foo.dart",
							"version": null
						}
					}
				]
			},
			"kind": "quickfix.create.file",
			"title": "Create file 'foo.dart'"
		}
	]
}
1765278329698:Req: {
	"jsonrpc": "2.0",
	"method": "textDocument/didOpen",
	"params": {
		"textDocument": {
			"uri": "file:///D%3A/Dev/Temp%20Projects/essential_lints/essential_lints_annotations/lib/src/sorting_members/foo.dart",
			"languageId": "dart",
			"version": 2,
			"text": "part of 'sort_declarations.dart';\r\n\r\n"
		}
	},
	"clientRequestTime": 1765278329702
}
1765278329708:Req: {
	"jsonrpc": "2.0",
	"method": "textDocument/didChange",
	"params": {
		"textDocument": {
			"uri": "file:///D%3A/Dev/Temp%20Projects/essential_lints/essential_lints_annotations/lib/src/sorting_members/foo.dart",
			"version": 2
		},
		"contentChanges": [
			{
				"range": {
					"start": {
						"line": 0,
						"character": 0
					},
					"end": {
						"line": 0,
						"character": 0
					}
				},
				"rangeLength": 0,
				"text": "part of 'sort_declarations.dart';\r\n\r\n"
			}
		]
	},
	"clientRequestTime": 1765278329702
}
```

**Comment by DanTup** [comment]
This appears to be a bug in the VS Code LSP client when using `delayOpenNotifications`. If you switch back to the Stable version of the Dart extension the issue goes away.

I'm re-opening https://github.com/Dart-Code/Dart-Code/issues/5176 (and reverting that flag) and will file an issue against the VS Code LSP Client. There's nothing to do in the server.

**Comment by DanTup** [comment]
I pushed an updated pre-release of the Dart extension (v3.125.20251209) that removes `delayOpenNotifications=true` and will prevent this from happening (stable release was not affected).

I've opened https://github.com/microsoft/vscode-languageserver-node/issues/1695 about the underlying issue, as I'd still like to ultimately ship with `delayOpenNotifications=true` for some performance gains (particularly if using `onlyAnalyzeProjectsWithOpenFiles`, [which I'd like to remove](https://github.com/dart-lang/sdk/issues/61742)).

**Comment by DanTup** [comment]
The fix for this issue landed in the LSP client and I've re-enabled it in Dart-Code master (closing https://github.com/Dart-Code/Dart-Code/issues/5176). I've tested the issue above and it no longer occurs.

I will push a pre-release extension in the next few days so it can be more widely tested before the next stable extension release (around the end/start of the month).

**Comment by DanTup** [comment]
@FMorschel FYI, I pushed a new pre-release today that re-enables this; please let me know if you see any similar issues with it.

**Comment by FMorschel** [comment]
I've tested it with the pre-release, and the issue still seems to be fixed. Thanks!
